/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetUserFilesResponseMeta
    /// </summary>
    [DataContract(Name = "GetUserFilesResponse_meta")]
    public partial class GetUserFilesResponseMeta
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserFilesResponseMeta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetUserFilesResponseMeta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserFilesResponseMeta" /> class.
        /// </summary>
        /// <param name="page">page (required).</param>
        /// <param name="limit">limit (required).</param>
        /// <param name="total">total (required).</param>
        /// <param name="totalPages">totalPages (required).</param>
        /// <param name="hasMore">hasMore (required).</param>
        public GetUserFilesResponseMeta(decimal page = default, decimal limit = default, decimal total = default, decimal totalPages = default, bool hasMore = default)
        {
            this.Page = page;
            this.Limit = limit;
            this.Total = total;
            this.TotalPages = totalPages;
            this.HasMore = hasMore;
        }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [DataMember(Name = "page", IsRequired = true, EmitDefaultValue = true)]
        public decimal Page { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Gets or Sets TotalPages
        /// </summary>
        [DataMember(Name = "totalPages", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalPages { get; set; }

        /// <summary>
        /// Gets or Sets HasMore
        /// </summary>
        [DataMember(Name = "hasMore", IsRequired = true, EmitDefaultValue = true)]
        public bool HasMore { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetUserFilesResponseMeta {\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("  HasMore: ").Append(HasMore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Validates the model properties and returns a list of validation errors.
        /// </summary>
        /// <returns>A list of validation error messages. Empty list if valid.</returns>
        public List<string> ValidateModel()
        {
            var errors = new List<string>();
            return errors;
        }
    }

}
