/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ReplaceOrganizationGroupUsersRequestInput
    /// </summary>
    [DataContract(Name = "ReplaceOrganizationGroupUsersRequestInput")]
    public partial class ReplaceOrganizationGroupUsersRequestInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplaceOrganizationGroupUsersRequestInput" /> class.
        /// </summary>
        /// <param name="userIds">userIds.</param>
        public ReplaceOrganizationGroupUsersRequestInput(List<Guid> userIds = default)
        {
            this.UserIds = userIds;
        }

        /// <summary>
        /// Gets or Sets UserIds
        /// </summary>
        [DataMember(Name = "userIds", EmitDefaultValue = false)]
        public List<Guid> UserIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReplaceOrganizationGroupUsersRequestInput {\n");
            sb.Append("  UserIds: ").Append(UserIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Validates the model properties and returns a list of validation errors.
        /// </summary>
        /// <returns>A list of validation error messages. Empty list if valid.</returns>
        public List<string> ValidateModel()
        {
            var errors = new List<string>();
            return errors;
        }
    }

}
