/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// CourseAnalyticsOverviewResponseData
    /// </summary>
    [DataContract(Name = "CourseAnalyticsOverviewResponse_data")]
    public partial class CourseAnalyticsOverviewResponseData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CourseAnalyticsOverviewResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CourseAnalyticsOverviewResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CourseAnalyticsOverviewResponseData" /> class.
        /// </summary>
        /// <param name="courseId">courseId (required).</param>
        /// <param name="summary">summary (required).</param>
        /// <param name="completionOverTime">completionOverTime (required).</param>
        public CourseAnalyticsOverviewResponseData(Guid courseId = default, CourseListResponseDataInnerAnalytics summary = default, List<CourseAnalyticsOverviewResponseDataCompletionOverTimeInner> completionOverTime = default)
        {
            this.CourseId = courseId;
            // to ensure "summary" is required (not null)
            if (summary == null)
            {
                throw new ArgumentNullException("summary is a required property for CourseAnalyticsOverviewResponseData and cannot be null");
            }
            this.Summary = summary;
            // to ensure "completionOverTime" is required (not null)
            if (completionOverTime == null)
            {
                throw new ArgumentNullException("completionOverTime is a required property for CourseAnalyticsOverviewResponseData and cannot be null");
            }
            this.CompletionOverTime = completionOverTime;
        }

        /// <summary>
        /// Gets or Sets CourseId
        /// </summary>
        [DataMember(Name = "courseId", IsRequired = true, EmitDefaultValue = true)]
        public Guid CourseId { get; set; }

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [DataMember(Name = "summary", IsRequired = true, EmitDefaultValue = true)]
        public CourseListResponseDataInnerAnalytics Summary { get; set; }

        /// <summary>
        /// Gets or Sets CompletionOverTime
        /// </summary>
        [DataMember(Name = "completionOverTime", IsRequired = true, EmitDefaultValue = true)]
        public List<CourseAnalyticsOverviewResponseDataCompletionOverTimeInner> CompletionOverTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CourseAnalyticsOverviewResponseData {\n");
            sb.Append("  CourseId: ").Append(CourseId).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  CompletionOverTime: ").Append(CompletionOverTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Validates the model properties and returns a list of validation errors.
        /// </summary>
        /// <returns>A list of validation error messages. Empty list if valid.</returns>
        public List<string> ValidateModel()
        {
            var errors = new List<string>();
                // CourseId (Guid) pattern
                Regex regexCourseId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);
                if (!regexCourseId.Match(this.CourseId.ToString()).Success)
                {
                    errors.Add("Invalid value for CourseId, must match a pattern of " + regexCourseId);
                }

            return errors;
        }
    }

}
