/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsUncitedFilesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsUncitedFilesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsUncitedFilesResponse
        //private AnalyticsUncitedFilesResponse instance;

        public AnalyticsUncitedFilesResponseTests()
        {
            // TODO uncomment below to create an instance of AnalyticsUncitedFilesResponse
            //instance = new AnalyticsUncitedFilesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsUncitedFilesResponse
        /// </summary>
        [Fact]
        public void AnalyticsUncitedFilesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsUncitedFilesResponse
            //Assert.IsType<AnalyticsUncitedFilesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

        /// <summary>
        /// Test the property 'TotalFiles'
        /// </summary>
        [Fact]
        public void TotalFilesTest()
        {
            // TODO unit test for the property 'TotalFiles'
        }

        /// <summary>
        /// Test the property 'CitedFiles'
        /// </summary>
        [Fact]
        public void CitedFilesTest()
        {
            // TODO unit test for the property 'CitedFiles'
        }
    }
}
