/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsSessionFeedbackRequestInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsSessionFeedbackRequestInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsSessionFeedbackRequestInput
        //private AnalyticsSessionFeedbackRequestInput instance;

        public AnalyticsSessionFeedbackRequestInputTests()
        {
            // TODO uncomment below to create an instance of AnalyticsSessionFeedbackRequestInput
            //instance = new AnalyticsSessionFeedbackRequestInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsSessionFeedbackRequestInput
        /// </summary>
        [Test]
        public void AnalyticsSessionFeedbackRequestInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsSessionFeedbackRequestInput
            //Assert.IsType<AnalyticsSessionFeedbackRequestInput>(instance);
        }

        /// <summary>
        /// Test the property 'ChatId'
        /// </summary>
        [Test]
        public void ChatIdTest()
        {
            // TODO unit test for the property 'ChatId'
        }
        /// <summary>
        /// Test the property 'Sentiment'
        /// </summary>
        [Test]
        public void SentimentTest()
        {
            // TODO unit test for the property 'Sentiment'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
    }
}
