/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsLatencyResponseInputDataSessionAveragesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsLatencyResponseInputDataSessionAveragesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsLatencyResponseInputDataSessionAveragesInner
        //private AnalyticsLatencyResponseInputDataSessionAveragesInner instance;

        public AnalyticsLatencyResponseInputDataSessionAveragesInnerTests()
        {
            // TODO uncomment below to create an instance of AnalyticsLatencyResponseInputDataSessionAveragesInner
            //instance = new AnalyticsLatencyResponseInputDataSessionAveragesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsLatencyResponseInputDataSessionAveragesInner
        /// </summary>
        [Test]
        public void AnalyticsLatencyResponseInputDataSessionAveragesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsLatencyResponseInputDataSessionAveragesInner
            //Assert.IsType<AnalyticsLatencyResponseInputDataSessionAveragesInner>(instance);
        }

        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Test]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'AverageLatency'
        /// </summary>
        [Test]
        public void AverageLatencyTest()
        {
            // TODO unit test for the property 'AverageLatency'
        }
        /// <summary>
        /// Test the property 'TraceCount'
        /// </summary>
        [Test]
        public void TraceCountTest()
        {
            // TODO unit test for the property 'TraceCount'
        }
    }
}
