/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsUserChatsResponseUsersInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsUserChatsResponseUsersInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsUserChatsResponseUsersInner
        //private AnalyticsUserChatsResponseUsersInner instance;

        public AnalyticsUserChatsResponseUsersInnerTests()
        {
            // TODO uncomment below to create an instance of AnalyticsUserChatsResponseUsersInner
            //instance = new AnalyticsUserChatsResponseUsersInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsUserChatsResponseUsersInner
        /// </summary>
        [Test]
        public void AnalyticsUserChatsResponseUsersInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsUserChatsResponseUsersInner
            //Assert.IsType<AnalyticsUserChatsResponseUsersInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Chats'
        /// </summary>
        [Test]
        public void ChatsTest()
        {
            // TODO unit test for the property 'Chats'
        }
    }
}
