/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsLatencyResponseDataSessionsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsLatencyResponseDataSessionsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsLatencyResponseDataSessionsInner
        //private AnalyticsLatencyResponseDataSessionsInner instance;

        public AnalyticsLatencyResponseDataSessionsInnerTests()
        {
            // TODO uncomment below to create an instance of AnalyticsLatencyResponseDataSessionsInner
            //instance = new AnalyticsLatencyResponseDataSessionsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsLatencyResponseDataSessionsInner
        /// </summary>
        [Fact]
        public void AnalyticsLatencyResponseDataSessionsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsLatencyResponseDataSessionsInner
            //Assert.IsType<AnalyticsLatencyResponseDataSessionsInner>(instance);
        }

        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }

        /// <summary>
        /// Test the property 'Traces'
        /// </summary>
        [Fact]
        public void TracesTest()
        {
            // TODO unit test for the property 'Traces'
        }
    }
}
