/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsAgentUsageRequestInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsAgentUsageRequestInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsAgentUsageRequestInput
        //private AnalyticsAgentUsageRequestInput instance;

        public AnalyticsAgentUsageRequestInputTests()
        {
            // TODO uncomment below to create an instance of AnalyticsAgentUsageRequestInput
            //instance = new AnalyticsAgentUsageRequestInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsAgentUsageRequestInput
        /// </summary>
        [Fact]
        public void AnalyticsAgentUsageRequestInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsAgentUsageRequestInput
            //Assert.IsType<AnalyticsAgentUsageRequestInput>(instance);
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }

        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

        /// <summary>
        /// Test the property 'IncludeArchived'
        /// </summary>
        [Fact]
        public void IncludeArchivedTest()
        {
            // TODO unit test for the property 'IncludeArchived'
        }
    }
}
