/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV1CoursesGetFiltersParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1CoursesGetFiltersParameterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV1CoursesGetFiltersParameter
        //private ApiV1CoursesGetFiltersParameter instance;

        public ApiV1CoursesGetFiltersParameterTests()
        {
            // TODO uncomment below to create an instance of ApiV1CoursesGetFiltersParameter
            //instance = new ApiV1CoursesGetFiltersParameter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV1CoursesGetFiltersParameter
        /// </summary>
        [Test]
        public void ApiV1CoursesGetFiltersParameterInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV1CoursesGetFiltersParameter
            //Assert.IsType<ApiV1CoursesGetFiltersParameter>(instance);
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Test]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'TopicId'
        /// </summary>
        [Test]
        public void TopicIdTest()
        {
            // TODO unit test for the property 'TopicId'
        }
        /// <summary>
        /// Test the property 'CourseId'
        /// </summary>
        [Test]
        public void CourseIdTest()
        {
            // TODO unit test for the property 'CourseId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Search'
        /// </summary>
        [Test]
        public void SearchTest()
        {
            // TODO unit test for the property 'Search'
        }
    }
}
