/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV1ModulesModuleIdLaunchGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1ModulesModuleIdLaunchGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV1ModulesModuleIdLaunchGet200Response
        //private ApiV1ModulesModuleIdLaunchGet200Response instance;

        public ApiV1ModulesModuleIdLaunchGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of ApiV1ModulesModuleIdLaunchGet200Response
            //instance = new ApiV1ModulesModuleIdLaunchGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV1ModulesModuleIdLaunchGet200Response
        /// </summary>
        [Test]
        public void ApiV1ModulesModuleIdLaunchGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV1ModulesModuleIdLaunchGet200Response
            //Assert.IsType<ApiV1ModulesModuleIdLaunchGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
