/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV1TopicsTopicIdCourseOrderPut200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1TopicsTopicIdCourseOrderPut200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV1TopicsTopicIdCourseOrderPut200ResponseData
        //private ApiV1TopicsTopicIdCourseOrderPut200ResponseData instance;

        public ApiV1TopicsTopicIdCourseOrderPut200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of ApiV1TopicsTopicIdCourseOrderPut200ResponseData
            //instance = new ApiV1TopicsTopicIdCourseOrderPut200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV1TopicsTopicIdCourseOrderPut200ResponseData
        /// </summary>
        [Fact]
        public void ApiV1TopicsTopicIdCourseOrderPut200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV1TopicsTopicIdCourseOrderPut200ResponseData
            //Assert.IsType<ApiV1TopicsTopicIdCourseOrderPut200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'TopicId'
        /// </summary>
        [Fact]
        public void TopicIdTest()
        {
            // TODO unit test for the property 'TopicId'
        }
    }
}
