/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ApiV1ModulesModuleIdXapiStatementsGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiV1ModulesModuleIdXapiStatementsGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiV1ModulesModuleIdXapiStatementsGet200Response
        //private ApiV1ModulesModuleIdXapiStatementsGet200Response instance;

        public ApiV1ModulesModuleIdXapiStatementsGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of ApiV1ModulesModuleIdXapiStatementsGet200Response
            //instance = new ApiV1ModulesModuleIdXapiStatementsGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiV1ModulesModuleIdXapiStatementsGet200Response
        /// </summary>
        [Fact]
        public void ApiV1ModulesModuleIdXapiStatementsGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiV1ModulesModuleIdXapiStatementsGet200Response
            //Assert.IsType<ApiV1ModulesModuleIdXapiStatementsGet200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Statements'
        /// </summary>
        [Fact]
        public void StatementsTest()
        {
            // TODO unit test for the property 'Statements'
        }

        /// <summary>
        /// Test the property 'More'
        /// </summary>
        [Fact]
        public void MoreTest()
        {
            // TODO unit test for the property 'More'
        }
    }
}
