/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CharacterKnowledgeFoldersUpdateRequestInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CharacterKnowledgeFoldersUpdateRequestInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CharacterKnowledgeFoldersUpdateRequestInput
        //private CharacterKnowledgeFoldersUpdateRequestInput instance;

        public CharacterKnowledgeFoldersUpdateRequestInputTests()
        {
            // TODO uncomment below to create an instance of CharacterKnowledgeFoldersUpdateRequestInput
            //instance = new CharacterKnowledgeFoldersUpdateRequestInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CharacterKnowledgeFoldersUpdateRequestInput
        /// </summary>
        [Fact]
        public void CharacterKnowledgeFoldersUpdateRequestInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" CharacterKnowledgeFoldersUpdateRequestInput
            //Assert.IsType<CharacterKnowledgeFoldersUpdateRequestInput>(instance);
        }

        /// <summary>
        /// Test the property 'FolderIds'
        /// </summary>
        [Fact]
        public void FolderIdsTest()
        {
            // TODO unit test for the property 'FolderIds'
        }
    }
}
