/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ConfirmPasswordResetResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfirmPasswordResetResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfirmPasswordResetResponse
        //private ConfirmPasswordResetResponse instance;

        public ConfirmPasswordResetResponseTests()
        {
            // TODO uncomment below to create an instance of ConfirmPasswordResetResponse
            //instance = new ConfirmPasswordResetResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfirmPasswordResetResponse
        /// </summary>
        [Test]
        public void ConfirmPasswordResetResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfirmPasswordResetResponse
            //Assert.IsType<ConfirmPasswordResetResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
