/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CourseAssignedUsersResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CourseAssignedUsersResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CourseAssignedUsersResponseData
        //private CourseAssignedUsersResponseData instance;

        public CourseAssignedUsersResponseDataTests()
        {
            // TODO uncomment below to create an instance of CourseAssignedUsersResponseData
            //instance = new CourseAssignedUsersResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CourseAssignedUsersResponseData
        /// </summary>
        [Test]
        public void CourseAssignedUsersResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CourseAssignedUsersResponseData
            //Assert.IsType<CourseAssignedUsersResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Test]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }
    }
}
