/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CourseAssignUsersResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CourseAssignUsersResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CourseAssignUsersResponseData
        //private CourseAssignUsersResponseData instance;

        public CourseAssignUsersResponseDataTests()
        {
            // TODO uncomment below to create an instance of CourseAssignUsersResponseData
            //instance = new CourseAssignUsersResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CourseAssignUsersResponseData
        /// </summary>
        [Fact]
        public void CourseAssignUsersResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CourseAssignUsersResponseData
            //Assert.IsType<CourseAssignUsersResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Assigned'
        /// </summary>
        [Fact]
        public void AssignedTest()
        {
            // TODO unit test for the property 'Assigned'
        }
    }
}
