/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateOrReuseChatResponseInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateOrReuseChatResponseInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateOrReuseChatResponseInput
        //private CreateOrReuseChatResponseInput instance;

        public CreateOrReuseChatResponseInputTests()
        {
            // TODO uncomment below to create an instance of CreateOrReuseChatResponseInput
            //instance = new CreateOrReuseChatResponseInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateOrReuseChatResponseInput
        /// </summary>
        [Fact]
        public void CreateOrReuseChatResponseInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateOrReuseChatResponseInput
            //Assert.IsType<CreateOrReuseChatResponseInput>(instance);
        }

        /// <summary>
        /// Test the property 'Chat'
        /// </summary>
        [Fact]
        public void ChatTest()
        {
            // TODO unit test for the property 'Chat'
        }

        /// <summary>
        /// Test the property 'Reused'
        /// </summary>
        [Fact]
        public void ReusedTest()
        {
            // TODO unit test for the property 'Reused'
        }
    }
}
