/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetAllHandbooksWithItemsResponseInputInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAllHandbooksWithItemsResponseInputInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAllHandbooksWithItemsResponseInputInner
        //private GetAllHandbooksWithItemsResponseInputInner instance;

        public GetAllHandbooksWithItemsResponseInputInnerTests()
        {
            // TODO uncomment below to create an instance of GetAllHandbooksWithItemsResponseInputInner
            //instance = new GetAllHandbooksWithItemsResponseInputInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAllHandbooksWithItemsResponseInputInner
        /// </summary>
        [Fact]
        public void GetAllHandbooksWithItemsResponseInputInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAllHandbooksWithItemsResponseInputInner
            //Assert.IsType<GetAllHandbooksWithItemsResponseInputInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'OrganizationName'
        /// </summary>
        [Fact]
        public void OrganizationNameTest()
        {
            // TODO unit test for the property 'OrganizationName'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
