/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetUserFilesResponseMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetUserFilesResponseMetaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetUserFilesResponseMeta
        //private GetUserFilesResponseMeta instance;

        public GetUserFilesResponseMetaTests()
        {
            // TODO uncomment below to create an instance of GetUserFilesResponseMeta
            //instance = new GetUserFilesResponseMeta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetUserFilesResponseMeta
        /// </summary>
        [Fact]
        public void GetUserFilesResponseMetaInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetUserFilesResponseMeta
            //Assert.IsType<GetUserFilesResponseMeta>(instance);
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }
    }
}
