/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing KnowledgeFolderCopyFilesResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnowledgeFolderCopyFilesResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KnowledgeFolderCopyFilesResponseData
        //private KnowledgeFolderCopyFilesResponseData instance;

        public KnowledgeFolderCopyFilesResponseDataTests()
        {
            // TODO uncomment below to create an instance of KnowledgeFolderCopyFilesResponseData
            //instance = new KnowledgeFolderCopyFilesResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KnowledgeFolderCopyFilesResponseData
        /// </summary>
        [Test]
        public void KnowledgeFolderCopyFilesResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" KnowledgeFolderCopyFilesResponseData
            //Assert.IsType<KnowledgeFolderCopyFilesResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'CopiedCount'
        /// </summary>
        [Test]
        public void CopiedCountTest()
        {
            // TODO unit test for the property 'CopiedCount'
        }
        /// <summary>
        /// Test the property 'CopiedFileIds'
        /// </summary>
        [Test]
        public void CopiedFileIdsTest()
        {
            // TODO unit test for the property 'CopiedFileIds'
        }
        /// <summary>
        /// Test the property 'TargetFolderId'
        /// </summary>
        [Test]
        public void TargetFolderIdTest()
        {
            // TODO unit test for the property 'TargetFolderId'
        }
    }
}
