/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing KnowledgeFolderListResponseDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnowledgeFolderListResponseDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KnowledgeFolderListResponseDataInner
        //private KnowledgeFolderListResponseDataInner instance;

        public KnowledgeFolderListResponseDataInnerTests()
        {
            // TODO uncomment below to create an instance of KnowledgeFolderListResponseDataInner
            //instance = new KnowledgeFolderListResponseDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KnowledgeFolderListResponseDataInner
        /// </summary>
        [Fact]
        public void KnowledgeFolderListResponseDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" KnowledgeFolderListResponseDataInner
            //Assert.IsType<KnowledgeFolderListResponseDataInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Fact]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Counts'
        /// </summary>
        [Fact]
        public void CountsTest()
        {
            // TODO unit test for the property 'Counts'
        }
    }
}
