/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing KnowledgeFolderDeleteResponseInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnowledgeFolderDeleteResponseInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KnowledgeFolderDeleteResponseInput
        //private KnowledgeFolderDeleteResponseInput instance;

        public KnowledgeFolderDeleteResponseInputTests()
        {
            // TODO uncomment below to create an instance of KnowledgeFolderDeleteResponseInput
            //instance = new KnowledgeFolderDeleteResponseInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KnowledgeFolderDeleteResponseInput
        /// </summary>
        [Test]
        public void KnowledgeFolderDeleteResponseInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" KnowledgeFolderDeleteResponseInput
            //Assert.IsType<KnowledgeFolderDeleteResponseInput>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
