/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing KnowledgeFolderListResponseInputDataInnerCounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KnowledgeFolderListResponseInputDataInnerCountsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KnowledgeFolderListResponseInputDataInnerCounts
        //private KnowledgeFolderListResponseInputDataInnerCounts instance;

        public KnowledgeFolderListResponseInputDataInnerCountsTests()
        {
            // TODO uncomment below to create an instance of KnowledgeFolderListResponseInputDataInnerCounts
            //instance = new KnowledgeFolderListResponseInputDataInnerCounts();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KnowledgeFolderListResponseInputDataInnerCounts
        /// </summary>
        [Fact]
        public void KnowledgeFolderListResponseInputDataInnerCountsInstanceTest()
        {
            // TODO uncomment below to test "IsType" KnowledgeFolderListResponseInputDataInnerCounts
            //Assert.IsType<KnowledgeFolderListResponseInputDataInnerCounts>(instance);
        }

        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

        /// <summary>
        /// Test the property 'Handbooks'
        /// </summary>
        [Fact]
        public void HandbooksTest()
        {
            // TODO unit test for the property 'Handbooks'
        }

        /// <summary>
        /// Test the property 'Characters'
        /// </summary>
        [Fact]
        public void CharactersTest()
        {
            // TODO unit test for the property 'Characters'
        }
    }
}
