/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner
        //private ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner instance;

        public ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInnerTests()
        {
            // TODO uncomment below to create an instance of ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner
            //instance = new ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner
        /// </summary>
        [Fact]
        public void ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner
            //Assert.IsType<ListMyTrainingResponseInputTopicsInnerCoursesInnerModulesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CourseId'
        /// </summary>
        [Fact]
        public void CourseIdTest()
        {
            // TODO unit test for the property 'CourseId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'PackageType'
        /// </summary>
        [Fact]
        public void PackageTypeTest()
        {
            // TODO unit test for the property 'PackageType'
        }

        /// <summary>
        /// Test the property 'ProgressPercent'
        /// </summary>
        [Fact]
        public void ProgressPercentTest()
        {
            // TODO unit test for the property 'ProgressPercent'
        }

        /// <summary>
        /// Test the property 'CompletionStatus'
        /// </summary>
        [Fact]
        public void CompletionStatusTest()
        {
            // TODO unit test for the property 'CompletionStatus'
        }

        /// <summary>
        /// Test the property 'ProgressState'
        /// </summary>
        [Fact]
        public void ProgressStateTest()
        {
            // TODO unit test for the property 'ProgressState'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ThumbnailUrl'
        /// </summary>
        [Fact]
        public void ThumbnailUrlTest()
        {
            // TODO unit test for the property 'ThumbnailUrl'
        }

        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }

        /// <summary>
        /// Test the property 'LastActivityAt'
        /// </summary>
        [Fact]
        public void LastActivityAtTest()
        {
            // TODO unit test for the property 'LastActivityAt'
        }

        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
    }
}
