/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing NotFoundErrorInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotFoundErrorInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotFoundErrorInput
        //private NotFoundErrorInput instance;

        public NotFoundErrorInputTests()
        {
            // TODO uncomment below to create an instance of NotFoundErrorInput
            //instance = new NotFoundErrorInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotFoundErrorInput
        /// </summary>
        [Fact]
        public void NotFoundErrorInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotFoundErrorInput
            //Assert.IsType<NotFoundErrorInput>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
