/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing OrganizationGroupReplaceUsersResponseInputData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrganizationGroupReplaceUsersResponseInputDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrganizationGroupReplaceUsersResponseInputData
        //private OrganizationGroupReplaceUsersResponseInputData instance;

        public OrganizationGroupReplaceUsersResponseInputDataTests()
        {
            // TODO uncomment below to create an instance of OrganizationGroupReplaceUsersResponseInputData
            //instance = new OrganizationGroupReplaceUsersResponseInputData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrganizationGroupReplaceUsersResponseInputData
        /// </summary>
        [Fact]
        public void OrganizationGroupReplaceUsersResponseInputDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrganizationGroupReplaceUsersResponseInputData
            //Assert.IsType<OrganizationGroupReplaceUsersResponseInputData>(instance);
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }

        /// <summary>
        /// Test the property 'UserIds'
        /// </summary>
        [Fact]
        public void UserIdsTest()
        {
            // TODO unit test for the property 'UserIds'
        }
    }
}
