/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetChatResponseInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetChatResponseInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetChatResponseInput
        //private GetChatResponseInput instance;

        public GetChatResponseInputTests()
        {
            // TODO uncomment below to create an instance of GetChatResponseInput
            //instance = new GetChatResponseInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetChatResponseInput
        /// </summary>
        [Test]
        public void GetChatResponseInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetChatResponseInput
            //Assert.IsType<GetChatResponseInput>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'CharacterId'
        /// </summary>
        [Test]
        public void CharacterIdTest()
        {
            // TODO unit test for the property 'CharacterId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'OpenaiThreadId'
        /// </summary>
        [Test]
        public void OpenaiThreadIdTest()
        {
            // TODO unit test for the property 'OpenaiThreadId'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
