/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing TTSSynthesizeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TTSSynthesizeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TTSSynthesizeRequest
        //private TTSSynthesizeRequest instance;

        public TTSSynthesizeRequestTests()
        {
            // TODO uncomment below to create an instance of TTSSynthesizeRequest
            //instance = new TTSSynthesizeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TTSSynthesizeRequest
        /// </summary>
        [Test]
        public void TTSSynthesizeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TTSSynthesizeRequest
            //Assert.IsType<TTSSynthesizeRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Voice'
        /// </summary>
        [Test]
        public void VoiceTest()
        {
            // TODO unit test for the property 'Voice'
        }
        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Test]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
    }
}
