/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AcademiiSdk.Api;
using AcademiiSdk.Model;
using AcademiiSdk.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace AcademiiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing UploadFileResponseInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UploadFileResponseInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UploadFileResponseInput
        //private UploadFileResponseInput instance;

        public UploadFileResponseInputTests()
        {
            // TODO uncomment below to create an instance of UploadFileResponseInput
            //instance = new UploadFileResponseInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UploadFileResponseInput
        /// </summary>
        [Test]
        public void UploadFileResponseInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" UploadFileResponseInput
            //Assert.IsType<UploadFileResponseInput>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Test]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }
        /// <summary>
        /// Test the property 'TotalUploaded'
        /// </summary>
        [Test]
        public void TotalUploadedTest()
        {
            // TODO unit test for the property 'TotalUploaded'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'UploadedFileIds'
        /// </summary>
        [Test]
        public void UploadedFileIdsTest()
        {
            // TODO unit test for the property 'UploadedFileIds'
        }
        /// <summary>
        /// Test the property 'StorageInfo'
        /// </summary>
        [Test]
        public void StorageInfoTest()
        {
            // TODO unit test for the property 'StorageInfo'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Test]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'PartialSuccess'
        /// </summary>
        [Test]
        public void PartialSuccessTest()
        {
            // TODO unit test for the property 'PartialSuccess'
        }
    }
}
