/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// AnalyticsUserUsageInput
    /// </summary>
    [DataContract(Name = "AnalyticsUserUsageInput")]
    public partial class AnalyticsUserUsageInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsUserUsageInput" /> class.
        /// </summary>
        /// <param name="sessionCount">sessionCount.</param>
        /// <param name="chatCount">chatCount.</param>
        /// <param name="avgResponseLatencyMs">avgResponseLatencyMs.</param>
        /// <param name="numberOfActiveChats">numberOfActiveChats.</param>
        /// <param name="activeUserCount">activeUserCount.</param>
        /// <param name="totalUserCount">totalUserCount.</param>
        /// <param name="totalEngagements">totalEngagements.</param>
        /// <param name="activeInteractions">activeInteractions.</param>
        public AnalyticsUserUsageInput(decimal sessionCount = default, decimal chatCount = default, decimal avgResponseLatencyMs = default, decimal numberOfActiveChats = default, decimal activeUserCount = default, decimal totalUserCount = default, decimal totalEngagements = default, decimal activeInteractions = default)
        {
            this.SessionCount = sessionCount;
            this.ChatCount = chatCount;
            this.AvgResponseLatencyMs = avgResponseLatencyMs;
            this.NumberOfActiveChats = numberOfActiveChats;
            this.ActiveUserCount = activeUserCount;
            this.TotalUserCount = totalUserCount;
            this.TotalEngagements = totalEngagements;
            this.ActiveInteractions = activeInteractions;
        }

        /// <summary>
        /// Gets or Sets SessionCount
        /// </summary>
        [DataMember(Name = "sessionCount", EmitDefaultValue = false)]
        public decimal SessionCount { get; set; }

        /// <summary>
        /// Gets or Sets ChatCount
        /// </summary>
        [DataMember(Name = "chatCount", EmitDefaultValue = false)]
        public decimal ChatCount { get; set; }

        /// <summary>
        /// Gets or Sets AvgResponseLatencyMs
        /// </summary>
        [DataMember(Name = "avgResponseLatencyMs", EmitDefaultValue = false)]
        public decimal AvgResponseLatencyMs { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfActiveChats
        /// </summary>
        [DataMember(Name = "numberOfActiveChats", EmitDefaultValue = false)]
        public decimal NumberOfActiveChats { get; set; }

        /// <summary>
        /// Gets or Sets ActiveUserCount
        /// </summary>
        [DataMember(Name = "activeUserCount", EmitDefaultValue = false)]
        public decimal ActiveUserCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalUserCount
        /// </summary>
        [DataMember(Name = "totalUserCount", EmitDefaultValue = false)]
        public decimal TotalUserCount { get; set; }

        /// <summary>
        /// Gets or Sets TotalEngagements
        /// </summary>
        [DataMember(Name = "totalEngagements", EmitDefaultValue = false)]
        public decimal TotalEngagements { get; set; }

        /// <summary>
        /// Gets or Sets ActiveInteractions
        /// </summary>
        [DataMember(Name = "activeInteractions", EmitDefaultValue = false)]
        public decimal ActiveInteractions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsUserUsageInput {\n");
            sb.Append("  SessionCount: ").Append(SessionCount).Append("\n");
            sb.Append("  ChatCount: ").Append(ChatCount).Append("\n");
            sb.Append("  AvgResponseLatencyMs: ").Append(AvgResponseLatencyMs).Append("\n");
            sb.Append("  NumberOfActiveChats: ").Append(NumberOfActiveChats).Append("\n");
            sb.Append("  ActiveUserCount: ").Append(ActiveUserCount).Append("\n");
            sb.Append("  TotalUserCount: ").Append(TotalUserCount).Append("\n");
            sb.Append("  TotalEngagements: ").Append(TotalEngagements).Append("\n");
            sb.Append("  ActiveInteractions: ").Append(ActiveInteractions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
