// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// AnalyticsInactiveUsersResponseInputUsersInner
    /// </summary>
    public partial class AnalyticsInactiveUsersResponseInputUsersInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsInactiveUsersResponseInputUsersInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="email">email</param>
        /// <param name="name">name</param>
        /// <param name="lastSeenAt">lastSeenAt</param>
        [JsonConstructor]
        public AnalyticsInactiveUsersResponseInputUsersInner(string id, string email, Option<string?> name = default, Option<string?> lastSeenAt = default)
        {
            Id = id;
            Email = email;
            NameOption = name;
            LastSeenAtOption = lastSeenAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastSeenAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastSeenAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastSeenAt
        /// </summary>
        [JsonPropertyName("lastSeenAt")]
        public string? LastSeenAt { get { return this.LastSeenAtOption; } set { this.LastSeenAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsInactiveUsersResponseInputUsersInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  LastSeenAt: ").Append(LastSeenAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AnalyticsInactiveUsersResponseInputUsersInner" />
    /// </summary>
    public class AnalyticsInactiveUsersResponseInputUsersInnerJsonConverter : JsonConverter<AnalyticsInactiveUsersResponseInputUsersInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="AnalyticsInactiveUsersResponseInputUsersInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AnalyticsInactiveUsersResponseInputUsersInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> email = default;
            Option<string?> name = default;
            Option<string?> lastSeenAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "lastSeenAt":
                            lastSeenAt = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class AnalyticsInactiveUsersResponseInputUsersInner.", nameof(id));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class AnalyticsInactiveUsersResponseInputUsersInner.", nameof(email));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class AnalyticsInactiveUsersResponseInputUsersInner.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class AnalyticsInactiveUsersResponseInputUsersInner.");

            return new AnalyticsInactiveUsersResponseInputUsersInner(id.Value!, email.Value!, name, lastSeenAt);
        }

        /// <summary>
        /// Serializes a <see cref="AnalyticsInactiveUsersResponseInputUsersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsInactiveUsersResponseInputUsersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AnalyticsInactiveUsersResponseInputUsersInner analyticsInactiveUsersResponseInputUsersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, analyticsInactiveUsersResponseInputUsersInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AnalyticsInactiveUsersResponseInputUsersInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsInactiveUsersResponseInputUsersInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AnalyticsInactiveUsersResponseInputUsersInner analyticsInactiveUsersResponseInputUsersInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (analyticsInactiveUsersResponseInputUsersInner.Id == null)
                throw new ArgumentNullException(nameof(analyticsInactiveUsersResponseInputUsersInner.Id), "Property is required for class AnalyticsInactiveUsersResponseInputUsersInner.");

            if (analyticsInactiveUsersResponseInputUsersInner.Email == null)
                throw new ArgumentNullException(nameof(analyticsInactiveUsersResponseInputUsersInner.Email), "Property is required for class AnalyticsInactiveUsersResponseInputUsersInner.");

            writer.WriteString("id", analyticsInactiveUsersResponseInputUsersInner.Id);

            writer.WriteString("email", analyticsInactiveUsersResponseInputUsersInner.Email);

            if (analyticsInactiveUsersResponseInputUsersInner.NameOption.IsSet)
                if (analyticsInactiveUsersResponseInputUsersInner.NameOption.Value != null)
                    writer.WriteString("name", analyticsInactiveUsersResponseInputUsersInner.Name);
                else
                    writer.WriteNull("name");

            if (analyticsInactiveUsersResponseInputUsersInner.LastSeenAtOption.IsSet)
                if (analyticsInactiveUsersResponseInputUsersInner.LastSeenAtOption.Value != null)
                    writer.WriteString("lastSeenAt", analyticsInactiveUsersResponseInputUsersInner.LastSeenAt);
                else
                    writer.WriteNull("lastSeenAt");
        }
    }
}
