// <auto-generated>
/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// AnalyticsSessionFeedbackRequest
    /// </summary>
    public partial class AnalyticsSessionFeedbackRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsSessionFeedbackRequest" /> class.
        /// </summary>
        /// <param name="chatId">chatId</param>
        /// <param name="sentiment">sentiment</param>
        /// <param name="comment">comment</param>
        [JsonConstructor]
        public AnalyticsSessionFeedbackRequest(Guid chatId, SentimentEnum sentiment, Option<string?> comment = default)
        {
            ChatId = chatId;
            Sentiment = sentiment;
            CommentOption = comment;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Sentiment
        /// </summary>
        public enum SentimentEnum
        {
            /// <summary>
            /// Enum Positive for value: positive
            /// </summary>
            Positive = 1,

            /// <summary>
            /// Enum Negative for value: negative
            /// </summary>
            Negative = 2
        }

        /// <summary>
        /// Returns a <see cref="SentimentEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static SentimentEnum SentimentEnumFromString(string value)
        {
            if (value.Equals("positive"))
                return SentimentEnum.Positive;

            if (value.Equals("negative"))
                return SentimentEnum.Negative;

            throw new NotImplementedException($"Could not convert value to type SentimentEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="SentimentEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SentimentEnum? SentimentEnumFromStringOrDefault(string value)
        {
            if (value.Equals("positive"))
                return SentimentEnum.Positive;

            if (value.Equals("negative"))
                return SentimentEnum.Negative;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SentimentEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string SentimentEnumToJsonValue(SentimentEnum value)
        {
            if (value == SentimentEnum.Positive)
                return "positive";

            if (value == SentimentEnum.Negative)
                return "negative";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Sentiment
        /// </summary>
        [JsonPropertyName("sentiment")]
        public SentimentEnum Sentiment { get; set; }

        /// <summary>
        /// Gets or Sets ChatId
        /// </summary>
        [JsonPropertyName("chatId")]
        public Guid ChatId { get; set; }

        /// <summary>
        /// Used to track the state of Comment
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CommentOption { get; private set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [JsonPropertyName("comment")]
        public string? Comment { get { return this.CommentOption; } set { this.CommentOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsSessionFeedbackRequest {\n");
            sb.Append("  ChatId: ").Append(ChatId).Append("\n");
            sb.Append("  Sentiment: ").Append(Sentiment).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ChatId (Guid) pattern
            Regex regexChatId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

            if (!regexChatId.Match(this.ChatId.ToString()).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ChatId, must match a pattern of " + regexChatId, new [] { "ChatId" });
            }
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AnalyticsSessionFeedbackRequest" />
    /// </summary>
    public class AnalyticsSessionFeedbackRequestJsonConverter : JsonConverter<AnalyticsSessionFeedbackRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="AnalyticsSessionFeedbackRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AnalyticsSessionFeedbackRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> chatId = default;
            Option<AnalyticsSessionFeedbackRequest.SentimentEnum?> sentiment = default;
            Option<string?> comment = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "chatId":
                            chatId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "sentiment":
                            string? sentimentRawValue = utf8JsonReader.GetString();
                            if (sentimentRawValue != null)
                                sentiment = new Option<AnalyticsSessionFeedbackRequest.SentimentEnum?>(AnalyticsSessionFeedbackRequest.SentimentEnumFromStringOrDefault(sentimentRawValue));
                            break;
                        case "comment":
                            comment = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!chatId.IsSet)
                throw new ArgumentException("Property is required for class AnalyticsSessionFeedbackRequest.", nameof(chatId));

            if (!sentiment.IsSet)
                throw new ArgumentException("Property is required for class AnalyticsSessionFeedbackRequest.", nameof(sentiment));

            if (chatId.IsSet && chatId.Value == null)
                throw new ArgumentNullException(nameof(chatId), "Property is not nullable for class AnalyticsSessionFeedbackRequest.");

            if (sentiment.IsSet && sentiment.Value == null)
                throw new ArgumentNullException(nameof(sentiment), "Property is not nullable for class AnalyticsSessionFeedbackRequest.");

            if (comment.IsSet && comment.Value == null)
                throw new ArgumentNullException(nameof(comment), "Property is not nullable for class AnalyticsSessionFeedbackRequest.");

            return new AnalyticsSessionFeedbackRequest(chatId.Value!.Value!, sentiment.Value!.Value!, comment);
        }

        /// <summary>
        /// Serializes a <see cref="AnalyticsSessionFeedbackRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsSessionFeedbackRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AnalyticsSessionFeedbackRequest analyticsSessionFeedbackRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, analyticsSessionFeedbackRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AnalyticsSessionFeedbackRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsSessionFeedbackRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AnalyticsSessionFeedbackRequest analyticsSessionFeedbackRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (analyticsSessionFeedbackRequest.CommentOption.IsSet && analyticsSessionFeedbackRequest.Comment == null)
                throw new ArgumentNullException(nameof(analyticsSessionFeedbackRequest.Comment), "Property is required for class AnalyticsSessionFeedbackRequest.");

            writer.WriteString("chatId", analyticsSessionFeedbackRequest.ChatId);

            var sentimentRawValue = AnalyticsSessionFeedbackRequest.SentimentEnumToJsonValue(analyticsSessionFeedbackRequest.Sentiment);
            writer.WriteString("sentiment", sentimentRawValue);
            if (analyticsSessionFeedbackRequest.CommentOption.IsSet)
                writer.WriteString("comment", analyticsSessionFeedbackRequest.Comment);
        }
    }
}
