/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// AnalyticsCitationsResponse
    /// </summary>
    [DataContract(Name = "AnalyticsCitationsResponse")]
    public partial class AnalyticsCitationsResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsCitationsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnalyticsCitationsResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsCitationsResponse" /> class.
        /// </summary>
        /// <param name="files">files (required).</param>
        public AnalyticsCitationsResponse(List<AnalyticsCitationsResponseFilesInner> files = default)
        {
            // to ensure "files" is required (not null)
            if (files == null)
            {
                throw new ArgumentNullException("files is a required property for AnalyticsCitationsResponse and cannot be null");
            }
            this.Files = files;
        }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [DataMember(Name = "files", IsRequired = true, EmitDefaultValue = true)]
        public List<AnalyticsCitationsResponseFilesInner> Files { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsCitationsResponse {\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
