/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// AnalyticsFileUsageExtremesResponse
    /// </summary>
    [DataContract(Name = "AnalyticsFileUsageExtremesResponse")]
    public partial class AnalyticsFileUsageExtremesResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsFileUsageExtremesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnalyticsFileUsageExtremesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsFileUsageExtremesResponse" /> class.
        /// </summary>
        /// <param name="mostUsed">mostUsed (required).</param>
        /// <param name="leastUsed">leastUsed (required).</param>
        public AnalyticsFileUsageExtremesResponse(List<AnalyticsFileUsageExtremesResponseMostUsedInner> mostUsed = default, List<AnalyticsFileUsageExtremesResponseMostUsedInner> leastUsed = default)
        {
            // to ensure "mostUsed" is required (not null)
            if (mostUsed == null)
            {
                throw new ArgumentNullException("mostUsed is a required property for AnalyticsFileUsageExtremesResponse and cannot be null");
            }
            this.MostUsed = mostUsed;
            // to ensure "leastUsed" is required (not null)
            if (leastUsed == null)
            {
                throw new ArgumentNullException("leastUsed is a required property for AnalyticsFileUsageExtremesResponse and cannot be null");
            }
            this.LeastUsed = leastUsed;
        }

        /// <summary>
        /// Gets or Sets MostUsed
        /// </summary>
        [DataMember(Name = "mostUsed", IsRequired = true, EmitDefaultValue = true)]
        public List<AnalyticsFileUsageExtremesResponseMostUsedInner> MostUsed { get; set; }

        /// <summary>
        /// Gets or Sets LeastUsed
        /// </summary>
        [DataMember(Name = "leastUsed", IsRequired = true, EmitDefaultValue = true)]
        public List<AnalyticsFileUsageExtremesResponseMostUsedInner> LeastUsed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsFileUsageExtremesResponse {\n");
            sb.Append("  MostUsed: ").Append(MostUsed).Append("\n");
            sb.Append("  LeastUsed: ").Append(LeastUsed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
