/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// AnalyticsQuestionTopicsResponseInputTopicsInner
    /// </summary>
    [DataContract(Name = "AnalyticsQuestionTopicsResponseInput_topics_inner")]
    public partial class AnalyticsQuestionTopicsResponseInputTopicsInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsQuestionTopicsResponseInputTopicsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnalyticsQuestionTopicsResponseInputTopicsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsQuestionTopicsResponseInputTopicsInner" /> class.
        /// </summary>
        /// <param name="topic">topic (required).</param>
        /// <param name="count">count (required).</param>
        public AnalyticsQuestionTopicsResponseInputTopicsInner(string topic = default, decimal count = default)
        {
            // to ensure "topic" is required (not null)
            if (topic == null)
            {
                throw new ArgumentNullException("topic is a required property for AnalyticsQuestionTopicsResponseInputTopicsInner and cannot be null");
            }
            this.Topic = topic;
            this.Count = count;
        }

        /// <summary>
        /// Gets or Sets Topic
        /// </summary>
        [DataMember(Name = "topic", IsRequired = true, EmitDefaultValue = true)]
        public string Topic { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [DataMember(Name = "count", IsRequired = true, EmitDefaultValue = true)]
        public decimal Count { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsQuestionTopicsResponseInputTopicsInner {\n");
            sb.Append("  Topic: ").Append(Topic).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
