// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// AnalyticsFeedbackResponseInputFeedbackInner
    /// </summary>
    public partial class AnalyticsFeedbackResponseInputFeedbackInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsFeedbackResponseInputFeedbackInner" /> class.
        /// </summary>
        /// <param name="targetId">targetId</param>
        /// <param name="count">count</param>
        /// <param name="targetType">targetType</param>
        /// <param name="averageScore">averageScore</param>
        /// <param name="comments">comments</param>
        [JsonConstructor]
        public AnalyticsFeedbackResponseInputFeedbackInner(string targetId, decimal count, Option<TargetTypeEnum?> targetType = default, Option<decimal?> averageScore = default, Option<List<string>?> comments = default)
        {
            TargetId = targetId;
            Count = count;
            TargetTypeOption = targetType;
            AverageScoreOption = averageScore;
            CommentsOption = comments;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines TargetType
        /// </summary>
        public enum TargetTypeEnum
        {
            /// <summary>
            /// Enum File for value: file
            /// </summary>
            File = 1,

            /// <summary>
            /// Enum Response for value: response
            /// </summary>
            Response = 2,

            /// <summary>
            /// Enum Chat for value: chat
            /// </summary>
            Chat = 3
        }

        /// <summary>
        /// Returns a <see cref="TargetTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TargetTypeEnum TargetTypeEnumFromString(string value)
        {
            if (value.Equals("file"))
                return TargetTypeEnum.File;

            if (value.Equals("response"))
                return TargetTypeEnum.Response;

            if (value.Equals("chat"))
                return TargetTypeEnum.Chat;

            throw new NotImplementedException($"Could not convert value to type TargetTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TargetTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TargetTypeEnum? TargetTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("file"))
                return TargetTypeEnum.File;

            if (value.Equals("response"))
                return TargetTypeEnum.Response;

            if (value.Equals("chat"))
                return TargetTypeEnum.Chat;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TargetTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TargetTypeEnumToJsonValue(TargetTypeEnum? value)
        {
            if (value == TargetTypeEnum.File)
                return "file";

            if (value == TargetTypeEnum.Response)
                return "response";

            if (value == TargetTypeEnum.Chat)
                return "chat";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of TargetType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TargetTypeEnum?> TargetTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets TargetType
        /// </summary>
        [JsonPropertyName("targetType")]
        public TargetTypeEnum? TargetType { get { return this.TargetTypeOption.Value; } set { this.TargetTypeOption = new(value); } }

        /// <summary>
        /// Gets or Sets TargetId
        /// </summary>
        [JsonPropertyName("targetId")]
        public string TargetId { get; set; }

        /// <summary>
        /// Gets or Sets Count
        /// </summary>
        [JsonPropertyName("count")]
        public decimal Count { get; set; }

        /// <summary>
        /// Used to track the state of AverageScore
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> AverageScoreOption { get; private set; }

        /// <summary>
        /// Gets or Sets AverageScore
        /// </summary>
        [JsonPropertyName("averageScore")]
        public decimal? AverageScore { get { return this.AverageScoreOption; } set { this.AverageScoreOption = new(value); } }

        /// <summary>
        /// Used to track the state of Comments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> CommentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [JsonPropertyName("comments")]
        public List<string>? Comments { get { return this.CommentsOption; } set { this.CommentsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsFeedbackResponseInputFeedbackInner {\n");
            sb.Append("  TargetId: ").Append(TargetId).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  TargetType: ").Append(TargetType).Append("\n");
            sb.Append("  AverageScore: ").Append(AverageScore).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AnalyticsFeedbackResponseInputFeedbackInner" />
    /// </summary>
    public class AnalyticsFeedbackResponseInputFeedbackInnerJsonConverter : JsonConverter<AnalyticsFeedbackResponseInputFeedbackInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="AnalyticsFeedbackResponseInputFeedbackInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AnalyticsFeedbackResponseInputFeedbackInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> targetId = default;
            Option<decimal?> count = default;
            Option<AnalyticsFeedbackResponseInputFeedbackInner.TargetTypeEnum?> targetType = default;
            Option<decimal?> averageScore = default;
            Option<List<string>?> comments = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "targetId":
                            targetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "count":
                            count = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "targetType":
                            string? targetTypeRawValue = utf8JsonReader.GetString();
                            if (targetTypeRawValue != null)
                                targetType = new Option<AnalyticsFeedbackResponseInputFeedbackInner.TargetTypeEnum?>(AnalyticsFeedbackResponseInputFeedbackInner.TargetTypeEnumFromStringOrDefault(targetTypeRawValue));
                            break;
                        case "averageScore":
                            averageScore = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "comments":
                            comments = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!targetId.IsSet)
                throw new ArgumentException("Property is required for class AnalyticsFeedbackResponseInputFeedbackInner.", nameof(targetId));

            if (!count.IsSet)
                throw new ArgumentException("Property is required for class AnalyticsFeedbackResponseInputFeedbackInner.", nameof(count));

            if (targetId.IsSet && targetId.Value == null)
                throw new ArgumentNullException(nameof(targetId), "Property is not nullable for class AnalyticsFeedbackResponseInputFeedbackInner.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class AnalyticsFeedbackResponseInputFeedbackInner.");

            if (targetType.IsSet && targetType.Value == null)
                throw new ArgumentNullException(nameof(targetType), "Property is not nullable for class AnalyticsFeedbackResponseInputFeedbackInner.");

            if (averageScore.IsSet && averageScore.Value == null)
                throw new ArgumentNullException(nameof(averageScore), "Property is not nullable for class AnalyticsFeedbackResponseInputFeedbackInner.");

            if (comments.IsSet && comments.Value == null)
                throw new ArgumentNullException(nameof(comments), "Property is not nullable for class AnalyticsFeedbackResponseInputFeedbackInner.");

            return new AnalyticsFeedbackResponseInputFeedbackInner(targetId.Value!, count.Value!.Value!, targetType, averageScore, comments);
        }

        /// <summary>
        /// Serializes a <see cref="AnalyticsFeedbackResponseInputFeedbackInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsFeedbackResponseInputFeedbackInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AnalyticsFeedbackResponseInputFeedbackInner analyticsFeedbackResponseInputFeedbackInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, analyticsFeedbackResponseInputFeedbackInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AnalyticsFeedbackResponseInputFeedbackInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsFeedbackResponseInputFeedbackInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AnalyticsFeedbackResponseInputFeedbackInner analyticsFeedbackResponseInputFeedbackInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (analyticsFeedbackResponseInputFeedbackInner.TargetId == null)
                throw new ArgumentNullException(nameof(analyticsFeedbackResponseInputFeedbackInner.TargetId), "Property is required for class AnalyticsFeedbackResponseInputFeedbackInner.");

            if (analyticsFeedbackResponseInputFeedbackInner.CommentsOption.IsSet && analyticsFeedbackResponseInputFeedbackInner.Comments == null)
                throw new ArgumentNullException(nameof(analyticsFeedbackResponseInputFeedbackInner.Comments), "Property is required for class AnalyticsFeedbackResponseInputFeedbackInner.");

            writer.WriteString("targetId", analyticsFeedbackResponseInputFeedbackInner.TargetId);

            writer.WriteNumber("count", analyticsFeedbackResponseInputFeedbackInner.Count);

            var targetTypeRawValue = AnalyticsFeedbackResponseInputFeedbackInner.TargetTypeEnumToJsonValue(analyticsFeedbackResponseInputFeedbackInner.TargetTypeOption.Value!.Value);
            writer.WriteString("targetType", targetTypeRawValue);
            if (analyticsFeedbackResponseInputFeedbackInner.AverageScoreOption.IsSet)
                writer.WriteNumber("averageScore", analyticsFeedbackResponseInputFeedbackInner.AverageScoreOption.Value!.Value);

            if (analyticsFeedbackResponseInputFeedbackInner.CommentsOption.IsSet)
            {
                writer.WritePropertyName("comments");
                JsonSerializer.Serialize(writer, analyticsFeedbackResponseInputFeedbackInner.Comments, jsonSerializerOptions);
            }
        }
    }
}
