/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ApiV1TopicsTopicIdCourseOrderPutRequest
    /// </summary>
    [DataContract(Name = "_api_v1_topics__topicId__course_order_put_request")]
    public partial class ApiV1TopicsTopicIdCourseOrderPutRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1TopicsTopicIdCourseOrderPutRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiV1TopicsTopicIdCourseOrderPutRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1TopicsTopicIdCourseOrderPutRequest" /> class.
        /// </summary>
        /// <param name="courseId">courseId (required).</param>
        /// <param name="beforeCourseId">beforeCourseId.</param>
        /// <param name="afterCourseId">afterCourseId.</param>
        public ApiV1TopicsTopicIdCourseOrderPutRequest(Guid courseId = default, Guid? beforeCourseId = default, Guid? afterCourseId = default)
        {
            this.CourseId = courseId;
            this.BeforeCourseId = beforeCourseId;
            this.AfterCourseId = afterCourseId;
        }

        /// <summary>
        /// Gets or Sets CourseId
        /// </summary>
        [DataMember(Name = "courseId", IsRequired = true, EmitDefaultValue = true)]
        public Guid CourseId { get; set; }

        /// <summary>
        /// Gets or Sets BeforeCourseId
        /// </summary>
        [DataMember(Name = "beforeCourseId", EmitDefaultValue = true)]
        public Guid? BeforeCourseId { get; set; }

        /// <summary>
        /// Gets or Sets AfterCourseId
        /// </summary>
        [DataMember(Name = "afterCourseId", EmitDefaultValue = true)]
        public Guid? AfterCourseId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1TopicsTopicIdCourseOrderPutRequest {\n");
            sb.Append("  CourseId: ").Append(CourseId).Append("\n");
            sb.Append("  BeforeCourseId: ").Append(BeforeCourseId).Append("\n");
            sb.Append("  AfterCourseId: ").Append(AfterCourseId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
