// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ApiV1TopicsTopicIdCourseOrderPutRequest
    /// </summary>
    public partial class ApiV1TopicsTopicIdCourseOrderPutRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1TopicsTopicIdCourseOrderPutRequest" /> class.
        /// </summary>
        /// <param name="courseId">courseId</param>
        /// <param name="beforeCourseId">beforeCourseId</param>
        /// <param name="afterCourseId">afterCourseId</param>
        [JsonConstructor]
        public ApiV1TopicsTopicIdCourseOrderPutRequest(Guid courseId, Option<Guid?> beforeCourseId = default, Option<Guid?> afterCourseId = default)
        {
            CourseId = courseId;
            BeforeCourseIdOption = beforeCourseId;
            AfterCourseIdOption = afterCourseId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CourseId
        /// </summary>
        [JsonPropertyName("courseId")]
        public Guid CourseId { get; set; }

        /// <summary>
        /// Used to track the state of BeforeCourseId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> BeforeCourseIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets BeforeCourseId
        /// </summary>
        [JsonPropertyName("beforeCourseId")]
        public Guid? BeforeCourseId { get { return this.BeforeCourseIdOption; } set { this.BeforeCourseIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of AfterCourseId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> AfterCourseIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets AfterCourseId
        /// </summary>
        [JsonPropertyName("afterCourseId")]
        public Guid? AfterCourseId { get { return this.AfterCourseIdOption; } set { this.AfterCourseIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1TopicsTopicIdCourseOrderPutRequest {\n");
            sb.Append("  CourseId: ").Append(CourseId).Append("\n");
            sb.Append("  BeforeCourseId: ").Append(BeforeCourseId).Append("\n");
            sb.Append("  AfterCourseId: ").Append(AfterCourseId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CourseId (Guid) pattern
            Regex regexCourseId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

            if (!regexCourseId.Match(this.CourseId.ToString()).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CourseId, must match a pattern of " + regexCourseId, new [] { "CourseId" });
            }
            if (this.BeforeCourseIdOption.Value != null){
                // BeforeCourseId (Guid) pattern
                Regex regexBeforeCourseId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

                if (this.BeforeCourseIdOption.Value != null &&!regexBeforeCourseId.Match(this.BeforeCourseIdOption.Value.ToString()!).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for BeforeCourseId, must match a pattern of " + regexBeforeCourseId, new [] { "BeforeCourseId" });
                }
            }

            if (this.AfterCourseIdOption.Value != null){
                // AfterCourseId (Guid) pattern
                Regex regexAfterCourseId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

                if (this.AfterCourseIdOption.Value != null &&!regexAfterCourseId.Match(this.AfterCourseIdOption.Value.ToString()!).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AfterCourseId, must match a pattern of " + regexAfterCourseId, new [] { "AfterCourseId" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiV1TopicsTopicIdCourseOrderPutRequest" />
    /// </summary>
    public class ApiV1TopicsTopicIdCourseOrderPutRequestJsonConverter : JsonConverter<ApiV1TopicsTopicIdCourseOrderPutRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiV1TopicsTopicIdCourseOrderPutRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiV1TopicsTopicIdCourseOrderPutRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> courseId = default;
            Option<Guid?> beforeCourseId = default;
            Option<Guid?> afterCourseId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "courseId":
                            courseId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "beforeCourseId":
                            beforeCourseId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "afterCourseId":
                            afterCourseId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!courseId.IsSet)
                throw new ArgumentException("Property is required for class ApiV1TopicsTopicIdCourseOrderPutRequest.", nameof(courseId));

            if (courseId.IsSet && courseId.Value == null)
                throw new ArgumentNullException(nameof(courseId), "Property is not nullable for class ApiV1TopicsTopicIdCourseOrderPutRequest.");

            return new ApiV1TopicsTopicIdCourseOrderPutRequest(courseId.Value!.Value!, beforeCourseId, afterCourseId);
        }

        /// <summary>
        /// Serializes a <see cref="ApiV1TopicsTopicIdCourseOrderPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1TopicsTopicIdCourseOrderPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiV1TopicsTopicIdCourseOrderPutRequest apiV1TopicsTopicIdCourseOrderPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiV1TopicsTopicIdCourseOrderPutRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiV1TopicsTopicIdCourseOrderPutRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1TopicsTopicIdCourseOrderPutRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiV1TopicsTopicIdCourseOrderPutRequest apiV1TopicsTopicIdCourseOrderPutRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("courseId", apiV1TopicsTopicIdCourseOrderPutRequest.CourseId);

            if (apiV1TopicsTopicIdCourseOrderPutRequest.BeforeCourseIdOption.IsSet)
                if (apiV1TopicsTopicIdCourseOrderPutRequest.BeforeCourseIdOption.Value != null)
                    writer.WriteString("beforeCourseId", apiV1TopicsTopicIdCourseOrderPutRequest.BeforeCourseIdOption.Value!.Value);
                else
                    writer.WriteNull("beforeCourseId");

            if (apiV1TopicsTopicIdCourseOrderPutRequest.AfterCourseIdOption.IsSet)
                if (apiV1TopicsTopicIdCourseOrderPutRequest.AfterCourseIdOption.Value != null)
                    writer.WriteString("afterCourseId", apiV1TopicsTopicIdCourseOrderPutRequest.AfterCourseIdOption.Value!.Value);
                else
                    writer.WriteNull("afterCourseId");
        }
    }
}
