// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ApiV1TopicsTopicIdPatchRequest
    /// </summary>
    public partial class ApiV1TopicsTopicIdPatchRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1TopicsTopicIdPatchRequest" /> class.
        /// </summary>
        /// <param name="enforceCourseOrder">enforceCourseOrder</param>
        /// <param name="name">name</param>
        /// <param name="description">description</param>
        /// <param name="sortOrder">sortOrder</param>
        /// <param name="isActive">isActive</param>
        [JsonConstructor]
        public ApiV1TopicsTopicIdPatchRequest(bool enforceCourseOrder, Option<string?> name = default, Option<string?> description = default, Option<long?> sortOrder = default, Option<bool?> isActive = default)
        {
            EnforceCourseOrder = enforceCourseOrder;
            NameOption = name;
            DescriptionOption = description;
            SortOrderOption = sortOrder;
            IsActiveOption = isActive;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets EnforceCourseOrder
        /// </summary>
        [JsonPropertyName("enforceCourseOrder")]
        public bool EnforceCourseOrder { get; set; }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of SortOrder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SortOrderOption { get; private set; }

        /// <summary>
        /// Gets or Sets SortOrder
        /// </summary>
        [JsonPropertyName("sortOrder")]
        public long? SortOrder { get { return this.SortOrderOption; } set { this.SortOrderOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1TopicsTopicIdPatchRequest {\n");
            sb.Append("  EnforceCourseOrder: ").Append(EnforceCourseOrder).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  SortOrder: ").Append(SortOrder).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Description, length must be greater than 1.", new [] { "Description" });
            }

            // SortOrder (long) maximum
            if (this.SortOrderOption.IsSet && this.SortOrderOption.Value > (long)9007199254740991)
            {
                yield return new ValidationResult("Invalid value for SortOrder, must be a value less than or equal to 9007199254740991.", new [] { "SortOrder" });
            }

            // SortOrder (long) minimum
            if (this.SortOrderOption.IsSet && this.SortOrderOption.Value < (long)0)
            {
                yield return new ValidationResult("Invalid value for SortOrder, must be a value greater than or equal to 0.", new [] { "SortOrder" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiV1TopicsTopicIdPatchRequest" />
    /// </summary>
    public class ApiV1TopicsTopicIdPatchRequestJsonConverter : JsonConverter<ApiV1TopicsTopicIdPatchRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiV1TopicsTopicIdPatchRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiV1TopicsTopicIdPatchRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> enforceCourseOrder = default;
            Option<string?> name = default;
            Option<string?> description = default;
            Option<long?> sortOrder = default;
            Option<bool?> isActive = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "enforceCourseOrder":
                            enforceCourseOrder = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sortOrder":
                            sortOrder = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!enforceCourseOrder.IsSet)
                throw new ArgumentException("Property is required for class ApiV1TopicsTopicIdPatchRequest.", nameof(enforceCourseOrder));

            if (enforceCourseOrder.IsSet && enforceCourseOrder.Value == null)
                throw new ArgumentNullException(nameof(enforceCourseOrder), "Property is not nullable for class ApiV1TopicsTopicIdPatchRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ApiV1TopicsTopicIdPatchRequest.");

            if (sortOrder.IsSet && sortOrder.Value == null)
                throw new ArgumentNullException(nameof(sortOrder), "Property is not nullable for class ApiV1TopicsTopicIdPatchRequest.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class ApiV1TopicsTopicIdPatchRequest.");

            return new ApiV1TopicsTopicIdPatchRequest(enforceCourseOrder.Value!.Value!, name, description, sortOrder, isActive);
        }

        /// <summary>
        /// Serializes a <see cref="ApiV1TopicsTopicIdPatchRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1TopicsTopicIdPatchRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiV1TopicsTopicIdPatchRequest apiV1TopicsTopicIdPatchRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiV1TopicsTopicIdPatchRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiV1TopicsTopicIdPatchRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1TopicsTopicIdPatchRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiV1TopicsTopicIdPatchRequest apiV1TopicsTopicIdPatchRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiV1TopicsTopicIdPatchRequest.NameOption.IsSet && apiV1TopicsTopicIdPatchRequest.Name == null)
                throw new ArgumentNullException(nameof(apiV1TopicsTopicIdPatchRequest.Name), "Property is required for class ApiV1TopicsTopicIdPatchRequest.");

            writer.WriteBoolean("enforceCourseOrder", apiV1TopicsTopicIdPatchRequest.EnforceCourseOrder);

            if (apiV1TopicsTopicIdPatchRequest.NameOption.IsSet)
                writer.WriteString("name", apiV1TopicsTopicIdPatchRequest.Name);

            if (apiV1TopicsTopicIdPatchRequest.DescriptionOption.IsSet)
                if (apiV1TopicsTopicIdPatchRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", apiV1TopicsTopicIdPatchRequest.Description);
                else
                    writer.WriteNull("description");

            if (apiV1TopicsTopicIdPatchRequest.SortOrderOption.IsSet)
                writer.WriteNumber("sortOrder", apiV1TopicsTopicIdPatchRequest.SortOrderOption.Value!.Value);

            if (apiV1TopicsTopicIdPatchRequest.IsActiveOption.IsSet)
                writer.WriteBoolean("isActive", apiV1TopicsTopicIdPatchRequest.IsActiveOption.Value!.Value);
        }
    }
}
