/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ApiV1FilesBulkDeletePostRequest
    /// </summary>
    [DataContract(Name = "_api_v1_files_bulk_delete_post_request")]
    public partial class ApiV1FilesBulkDeletePostRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1FilesBulkDeletePostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ApiV1FilesBulkDeletePostRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1FilesBulkDeletePostRequest" /> class.
        /// </summary>
        /// <param name="fileIds">fileIds (required).</param>
        /// <param name="organizationId">organizationId.</param>
        public ApiV1FilesBulkDeletePostRequest(List<Guid> fileIds = default, Guid organizationId = default)
        {
            // to ensure "fileIds" is required (not null)
            if (fileIds == null)
            {
                throw new ArgumentNullException("fileIds is a required property for ApiV1FilesBulkDeletePostRequest and cannot be null");
            }
            this.FileIds = fileIds;
            this.OrganizationId = organizationId;
        }

        /// <summary>
        /// Gets or Sets FileIds
        /// </summary>
        [DataMember(Name = "fileIds", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> FileIds { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name = "organizationId", EmitDefaultValue = false)]
        public Guid OrganizationId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1FilesBulkDeletePostRequest {\n");
            sb.Append("  FileIds: ").Append(FileIds).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
