// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ApiV1HandbookPostRequest
    /// </summary>
    public partial class ApiV1HandbookPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1HandbookPostRequest" /> class.
        /// </summary>
        /// <param name="title">title</param>
        /// <param name="url">url</param>
        /// <param name="description">description</param>
        /// <param name="organizationId">organizationId</param>
        /// <param name="handbookId">handbookId</param>
        [JsonConstructor]
        public ApiV1HandbookPostRequest(string title, string url, Option<string?> description = default, Option<string?> organizationId = default, Option<Guid?> handbookId = default)
        {
            Title = title;
            Url = url;
            DescriptionOption = description;
            OrganizationIdOption = organizationId;
            HandbookIdOption = handbookId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrganizationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrganizationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [JsonPropertyName("organizationId")]
        public string? OrganizationId { get { return this.OrganizationIdOption; } set { this.OrganizationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of HandbookId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> HandbookIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets HandbookId
        /// </summary>
        [JsonPropertyName("handbookId")]
        public Guid? HandbookId { get { return this.HandbookIdOption; } set { this.HandbookIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1HandbookPostRequest {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  HandbookId: ").Append(HandbookId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 500)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 500.", new [] { "Title" });
            }

            // Title (string) minLength
            if (this.Title != null && this.Title.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Title, length must be greater than 1.", new [] { "Title" });
            }

            // Url (string) maxLength
            if (this.Url != null && this.Url.Length > 2000)
            {
                yield return new ValidationResult("Invalid value for Url, length must be less than 2000.", new [] { "Url" });
            }

            // HandbookId (Guid) pattern
            Regex regexHandbookId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

            if (this.HandbookIdOption.Value != null &&!regexHandbookId.Match(this.HandbookIdOption.Value.ToString()!).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for HandbookId, must match a pattern of " + regexHandbookId, new [] { "HandbookId" });
            }
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiV1HandbookPostRequest" />
    /// </summary>
    public class ApiV1HandbookPostRequestJsonConverter : JsonConverter<ApiV1HandbookPostRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiV1HandbookPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiV1HandbookPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<string?> url = default;
            Option<string?> description = default;
            Option<string?> organizationId = default;
            Option<Guid?> handbookId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organizationId":
                            organizationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "handbookId":
                            handbookId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class ApiV1HandbookPostRequest.", nameof(title));

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class ApiV1HandbookPostRequest.", nameof(url));

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class ApiV1HandbookPostRequest.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class ApiV1HandbookPostRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ApiV1HandbookPostRequest.");

            if (organizationId.IsSet && organizationId.Value == null)
                throw new ArgumentNullException(nameof(organizationId), "Property is not nullable for class ApiV1HandbookPostRequest.");

            if (handbookId.IsSet && handbookId.Value == null)
                throw new ArgumentNullException(nameof(handbookId), "Property is not nullable for class ApiV1HandbookPostRequest.");

            return new ApiV1HandbookPostRequest(title.Value!, url.Value!, description, organizationId, handbookId);
        }

        /// <summary>
        /// Serializes a <see cref="ApiV1HandbookPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1HandbookPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiV1HandbookPostRequest apiV1HandbookPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiV1HandbookPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiV1HandbookPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1HandbookPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiV1HandbookPostRequest apiV1HandbookPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiV1HandbookPostRequest.Title == null)
                throw new ArgumentNullException(nameof(apiV1HandbookPostRequest.Title), "Property is required for class ApiV1HandbookPostRequest.");

            if (apiV1HandbookPostRequest.Url == null)
                throw new ArgumentNullException(nameof(apiV1HandbookPostRequest.Url), "Property is required for class ApiV1HandbookPostRequest.");

            if (apiV1HandbookPostRequest.DescriptionOption.IsSet && apiV1HandbookPostRequest.Description == null)
                throw new ArgumentNullException(nameof(apiV1HandbookPostRequest.Description), "Property is required for class ApiV1HandbookPostRequest.");

            if (apiV1HandbookPostRequest.OrganizationIdOption.IsSet && apiV1HandbookPostRequest.OrganizationId == null)
                throw new ArgumentNullException(nameof(apiV1HandbookPostRequest.OrganizationId), "Property is required for class ApiV1HandbookPostRequest.");

            writer.WriteString("title", apiV1HandbookPostRequest.Title);

            writer.WriteString("url", apiV1HandbookPostRequest.Url);

            if (apiV1HandbookPostRequest.DescriptionOption.IsSet)
                writer.WriteString("description", apiV1HandbookPostRequest.Description);

            if (apiV1HandbookPostRequest.OrganizationIdOption.IsSet)
                writer.WriteString("organizationId", apiV1HandbookPostRequest.OrganizationId);

            if (apiV1HandbookPostRequest.HandbookIdOption.IsSet)
                writer.WriteString("handbookId", apiV1HandbookPostRequest.HandbookIdOption.Value!.Value);
        }
    }
}
