/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ApiV1TopicsGetFiltersParameter
    /// </summary>
    [DataContract(Name = "_api_v1_topics_get_filters_parameter")]
    public partial class ApiV1TopicsGetFiltersParameter
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1TopicsGetFiltersParameter" /> class.
        /// </summary>
        /// <param name="organizationId">organizationId.</param>
        /// <param name="isActive">isActive.</param>
        /// <param name="search">search.</param>
        public ApiV1TopicsGetFiltersParameter(ApiV1TopicsGetFiltersParameterOrganizationId organizationId = default, ApiV1TopicsGetFiltersParameterIsActive isActive = default, ApiV1TopicsGetFiltersParameterSearch search = default)
        {
            this.OrganizationId = organizationId;
            this.IsActive = isActive;
            this.Search = search;
        }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name = "organizationId", EmitDefaultValue = false)]
        public ApiV1TopicsGetFiltersParameterOrganizationId OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name = "isActive", EmitDefaultValue = false)]
        public ApiV1TopicsGetFiltersParameterIsActive IsActive { get; set; }

        /// <summary>
        /// Gets or Sets Search
        /// </summary>
        [DataMember(Name = "search", EmitDefaultValue = false)]
        public ApiV1TopicsGetFiltersParameterSearch Search { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1TopicsGetFiltersParameter {\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  Search: ").Append(Search).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
