// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest
    /// </summary>
    public partial class ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest" /> class.
        /// </summary>
        /// <param name="handbookItemIds">handbookItemIds</param>
        [JsonConstructor]
        public ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest(List<Guid> handbookItemIds)
        {
            HandbookItemIds = handbookItemIds;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets HandbookItemIds
        /// </summary>
        [JsonPropertyName("handbookItemIds")]
        public List<Guid> HandbookItemIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest {\n");
            sb.Append("  HandbookItemIds: ").Append(HandbookItemIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest" />
    /// </summary>
    public class ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequestJsonConverter : JsonConverter<ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Guid>?> handbookItemIds = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "handbookItemIds":
                            handbookItemIds = new Option<List<Guid>?>(JsonSerializer.Deserialize<List<Guid>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!handbookItemIds.IsSet)
                throw new ArgumentException("Property is required for class ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest.", nameof(handbookItemIds));

            if (handbookItemIds.IsSet && handbookItemIds.Value == null)
                throw new ArgumentNullException(nameof(handbookItemIds), "Property is not nullable for class ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest.");

            return new ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest(handbookItemIds.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest.HandbookItemIds == null)
                throw new ArgumentNullException(nameof(apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest.HandbookItemIds), "Property is required for class ApiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest.");

            writer.WritePropertyName("handbookItemIds");
            JsonSerializer.Serialize(writer, apiV1CharactersIdKnowledgeHandbookItemsAttachPostRequest.HandbookItemIds, jsonSerializerOptions);
        }
    }
}
