/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// CharacterResponseModerationSettings
    /// </summary>
    [DataContract(Name = "CharacterResponse_moderationSettings")]
    public partial class CharacterResponseModerationSettings
    {
        /// <summary>
        /// Defines Level
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LevelEnum
        {
            /// <summary>
            /// Enum Strict for value: strict
            /// </summary>
            [EnumMember(Value = "strict")]
            Strict = 1,

            /// <summary>
            /// Enum Moderate for value: moderate
            /// </summary>
            [EnumMember(Value = "moderate")]
            Moderate = 2,

            /// <summary>
            /// Enum Relaxed for value: relaxed
            /// </summary>
            [EnumMember(Value = "relaxed")]
            Relaxed = 3
        }


        /// <summary>
        /// Gets or Sets Level
        /// </summary>
        [DataMember(Name = "level", IsRequired = true, EmitDefaultValue = true)]
        public LevelEnum Level { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CharacterResponseModerationSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CharacterResponseModerationSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CharacterResponseModerationSettings" /> class.
        /// </summary>
        /// <param name="enabled">enabled (required) (default to true).</param>
        /// <param name="level">level (required) (default to LevelEnum.Moderate).</param>
        /// <param name="customRules">customRules.</param>
        public CharacterResponseModerationSettings(bool enabled = true, LevelEnum level = LevelEnum.Moderate, List<string> customRules = default)
        {
            this.Enabled = enabled;
            this.Level = level;
            this.CustomRules = customRules;
        }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets CustomRules
        /// </summary>
        [DataMember(Name = "customRules", EmitDefaultValue = false)]
        public List<string> CustomRules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CharacterResponseModerationSettings {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Level: ").Append(Level).Append("\n");
            sb.Append("  CustomRules: ").Append(CustomRules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
