/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// CourseAnalyticsOverviewResponseDataCompletionOverTimeInner
    /// </summary>
    [DataContract(Name = "CourseAnalyticsOverviewResponse_data_completionOverTime_inner")]
    public partial class CourseAnalyticsOverviewResponseDataCompletionOverTimeInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CourseAnalyticsOverviewResponseDataCompletionOverTimeInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CourseAnalyticsOverviewResponseDataCompletionOverTimeInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CourseAnalyticsOverviewResponseDataCompletionOverTimeInner" /> class.
        /// </summary>
        /// <param name="date">date (required).</param>
        /// <param name="completedCount">completedCount (required).</param>
        public CourseAnalyticsOverviewResponseDataCompletionOverTimeInner(string date = default, int completedCount = default)
        {
            // to ensure "date" is required (not null)
            if (date == null)
            {
                throw new ArgumentNullException("date is a required property for CourseAnalyticsOverviewResponseDataCompletionOverTimeInner and cannot be null");
            }
            this.Date = date;
            this.CompletedCount = completedCount;
        }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name = "date", IsRequired = true, EmitDefaultValue = true)]
        public string Date { get; set; }

        /// <summary>
        /// Gets or Sets CompletedCount
        /// </summary>
        [DataMember(Name = "completedCount", IsRequired = true, EmitDefaultValue = true)]
        public long CompletedCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CourseAnalyticsOverviewResponseDataCompletionOverTimeInner {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  CompletedCount: ").Append(CompletedCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Validates the model properties and returns a list of validation errors.
        /// </summary>
        /// <returns>A list of validation error messages. Empty list if valid.</returns>
        public List<string> ValidateModel()
        {
            var errors = new List<string>();
            // CompletedCount (long) maximum
            if (this.CompletedCount > (long)9007199254740991)
            {
                errors.Add("Invalid value for CompletedCount, must be a value less than or equal to 9007199254740991.");
            }

            // CompletedCount (long) minimum
            if (this.CompletedCount < (long)0)
            {
                errors.Add("Invalid value for CompletedCount, must be a value greater than or equal to 0.");
            }

            return errors;
        }
    }

}
