// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// CreateCharacterRequest
    /// </summary>
    public partial class CreateCharacterRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCharacterRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="backstory">backstory</param>
        /// <param name="voiceId">voiceId</param>
        /// <param name="organizationId">organizationId</param>
        /// <param name="cameraPosition">cameraPosition</param>
        /// <param name="cameraRotation">cameraRotation</param>
        /// <param name="cameraFov">cameraFov</param>
        /// <param name="avatarRotation">avatarRotation</param>
        /// <param name="environmentPreset">environmentPreset</param>
        [JsonConstructor]
        public CreateCharacterRequest(string name, string backstory, Option<string?> voiceId = default, Option<string?> organizationId = default, Option<List<CreateCharacterRequestInputCameraPositionInner>?> cameraPosition = default, Option<List<CreateCharacterRequestInputCameraPositionInner>?> cameraRotation = default, Option<decimal?> cameraFov = default, Option<List<CreateCharacterRequestInputCameraPositionInner>?> avatarRotation = default, Option<string?> environmentPreset = default)
        {
            Name = name;
            Backstory = backstory;
            VoiceIdOption = voiceId;
            OrganizationIdOption = organizationId;
            CameraPositionOption = cameraPosition;
            CameraRotationOption = cameraRotation;
            CameraFovOption = cameraFov;
            AvatarRotationOption = avatarRotation;
            EnvironmentPresetOption = environmentPreset;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Backstory
        /// </summary>
        [JsonPropertyName("backstory")]
        public string Backstory { get; set; }

        /// <summary>
        /// Used to track the state of VoiceId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VoiceIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets VoiceId
        /// </summary>
        [JsonPropertyName("voiceId")]
        public string? VoiceId { get { return this.VoiceIdOption; } set { this.VoiceIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrganizationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrganizationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [JsonPropertyName("organizationId")]
        public string? OrganizationId { get { return this.OrganizationIdOption; } set { this.OrganizationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CameraPosition
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateCharacterRequestInputCameraPositionInner>?> CameraPositionOption { get; private set; }

        /// <summary>
        /// Gets or Sets CameraPosition
        /// </summary>
        [JsonPropertyName("cameraPosition")]
        public List<CreateCharacterRequestInputCameraPositionInner>? CameraPosition { get { return this.CameraPositionOption; } set { this.CameraPositionOption = new(value); } }

        /// <summary>
        /// Used to track the state of CameraRotation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateCharacterRequestInputCameraPositionInner>?> CameraRotationOption { get; private set; }

        /// <summary>
        /// Gets or Sets CameraRotation
        /// </summary>
        [JsonPropertyName("cameraRotation")]
        public List<CreateCharacterRequestInputCameraPositionInner>? CameraRotation { get { return this.CameraRotationOption; } set { this.CameraRotationOption = new(value); } }

        /// <summary>
        /// Used to track the state of CameraFov
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> CameraFovOption { get; private set; }

        /// <summary>
        /// Gets or Sets CameraFov
        /// </summary>
        [JsonPropertyName("cameraFov")]
        public decimal? CameraFov { get { return this.CameraFovOption; } set { this.CameraFovOption = new(value); } }

        /// <summary>
        /// Used to track the state of AvatarRotation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateCharacterRequestInputCameraPositionInner>?> AvatarRotationOption { get; private set; }

        /// <summary>
        /// Gets or Sets AvatarRotation
        /// </summary>
        [JsonPropertyName("avatarRotation")]
        public List<CreateCharacterRequestInputCameraPositionInner>? AvatarRotation { get { return this.AvatarRotationOption; } set { this.AvatarRotationOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnvironmentPreset
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EnvironmentPresetOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnvironmentPreset
        /// </summary>
        [JsonPropertyName("environmentPreset")]
        public string? EnvironmentPreset { get { return this.EnvironmentPresetOption; } set { this.EnvironmentPresetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCharacterRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Backstory: ").Append(Backstory).Append("\n");
            sb.Append("  VoiceId: ").Append(VoiceId).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  CameraPosition: ").Append(CameraPosition).Append("\n");
            sb.Append("  CameraRotation: ").Append(CameraRotation).Append("\n");
            sb.Append("  CameraFov: ").Append(CameraFov).Append("\n");
            sb.Append("  AvatarRotation: ").Append(AvatarRotation).Append("\n");
            sb.Append("  EnvironmentPreset: ").Append(EnvironmentPreset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Backstory (string) minLength
            if (this.Backstory != null && this.Backstory.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Backstory, length must be greater than 1.", new [] { "Backstory" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateCharacterRequest" />
    /// </summary>
    public class CreateCharacterRequestJsonConverter : JsonConverter<CreateCharacterRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateCharacterRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateCharacterRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> backstory = default;
            Option<string?> voiceId = default;
            Option<string?> organizationId = default;
            Option<List<CreateCharacterRequestInputCameraPositionInner>?> cameraPosition = default;
            Option<List<CreateCharacterRequestInputCameraPositionInner>?> cameraRotation = default;
            Option<decimal?> cameraFov = default;
            Option<List<CreateCharacterRequestInputCameraPositionInner>?> avatarRotation = default;
            Option<string?> environmentPreset = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "backstory":
                            backstory = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "voiceId":
                            voiceId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organizationId":
                            organizationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "cameraPosition":
                            cameraPosition = new Option<List<CreateCharacterRequestInputCameraPositionInner>?>(JsonSerializer.Deserialize<List<CreateCharacterRequestInputCameraPositionInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cameraRotation":
                            cameraRotation = new Option<List<CreateCharacterRequestInputCameraPositionInner>?>(JsonSerializer.Deserialize<List<CreateCharacterRequestInputCameraPositionInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "cameraFov":
                            cameraFov = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "avatarRotation":
                            avatarRotation = new Option<List<CreateCharacterRequestInputCameraPositionInner>?>(JsonSerializer.Deserialize<List<CreateCharacterRequestInputCameraPositionInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "environmentPreset":
                            environmentPreset = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateCharacterRequest.", nameof(name));

            if (!backstory.IsSet)
                throw new ArgumentException("Property is required for class CreateCharacterRequest.", nameof(backstory));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateCharacterRequest.");

            if (backstory.IsSet && backstory.Value == null)
                throw new ArgumentNullException(nameof(backstory), "Property is not nullable for class CreateCharacterRequest.");

            if (voiceId.IsSet && voiceId.Value == null)
                throw new ArgumentNullException(nameof(voiceId), "Property is not nullable for class CreateCharacterRequest.");

            if (organizationId.IsSet && organizationId.Value == null)
                throw new ArgumentNullException(nameof(organizationId), "Property is not nullable for class CreateCharacterRequest.");

            if (cameraPosition.IsSet && cameraPosition.Value == null)
                throw new ArgumentNullException(nameof(cameraPosition), "Property is not nullable for class CreateCharacterRequest.");

            if (cameraRotation.IsSet && cameraRotation.Value == null)
                throw new ArgumentNullException(nameof(cameraRotation), "Property is not nullable for class CreateCharacterRequest.");

            if (cameraFov.IsSet && cameraFov.Value == null)
                throw new ArgumentNullException(nameof(cameraFov), "Property is not nullable for class CreateCharacterRequest.");

            if (avatarRotation.IsSet && avatarRotation.Value == null)
                throw new ArgumentNullException(nameof(avatarRotation), "Property is not nullable for class CreateCharacterRequest.");

            if (environmentPreset.IsSet && environmentPreset.Value == null)
                throw new ArgumentNullException(nameof(environmentPreset), "Property is not nullable for class CreateCharacterRequest.");

            return new CreateCharacterRequest(name.Value!, backstory.Value!, voiceId, organizationId, cameraPosition, cameraRotation, cameraFov, avatarRotation, environmentPreset);
        }

        /// <summary>
        /// Serializes a <see cref="CreateCharacterRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createCharacterRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateCharacterRequest createCharacterRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createCharacterRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateCharacterRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createCharacterRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateCharacterRequest createCharacterRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createCharacterRequest.Name == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.Name), "Property is required for class CreateCharacterRequest.");

            if (createCharacterRequest.Backstory == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.Backstory), "Property is required for class CreateCharacterRequest.");

            if (createCharacterRequest.VoiceIdOption.IsSet && createCharacterRequest.VoiceId == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.VoiceId), "Property is required for class CreateCharacterRequest.");

            if (createCharacterRequest.OrganizationIdOption.IsSet && createCharacterRequest.OrganizationId == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.OrganizationId), "Property is required for class CreateCharacterRequest.");

            if (createCharacterRequest.CameraPositionOption.IsSet && createCharacterRequest.CameraPosition == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.CameraPosition), "Property is required for class CreateCharacterRequest.");

            if (createCharacterRequest.CameraRotationOption.IsSet && createCharacterRequest.CameraRotation == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.CameraRotation), "Property is required for class CreateCharacterRequest.");

            if (createCharacterRequest.AvatarRotationOption.IsSet && createCharacterRequest.AvatarRotation == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.AvatarRotation), "Property is required for class CreateCharacterRequest.");

            if (createCharacterRequest.EnvironmentPresetOption.IsSet && createCharacterRequest.EnvironmentPreset == null)
                throw new ArgumentNullException(nameof(createCharacterRequest.EnvironmentPreset), "Property is required for class CreateCharacterRequest.");

            writer.WriteString("name", createCharacterRequest.Name);

            writer.WriteString("backstory", createCharacterRequest.Backstory);

            if (createCharacterRequest.VoiceIdOption.IsSet)
                writer.WriteString("voiceId", createCharacterRequest.VoiceId);

            if (createCharacterRequest.OrganizationIdOption.IsSet)
                writer.WriteString("organizationId", createCharacterRequest.OrganizationId);

            if (createCharacterRequest.CameraPositionOption.IsSet)
            {
                writer.WritePropertyName("cameraPosition");
                JsonSerializer.Serialize(writer, createCharacterRequest.CameraPosition, jsonSerializerOptions);
            }
            if (createCharacterRequest.CameraRotationOption.IsSet)
            {
                writer.WritePropertyName("cameraRotation");
                JsonSerializer.Serialize(writer, createCharacterRequest.CameraRotation, jsonSerializerOptions);
            }
            if (createCharacterRequest.CameraFovOption.IsSet)
                writer.WriteNumber("cameraFov", createCharacterRequest.CameraFovOption.Value!.Value);

            if (createCharacterRequest.AvatarRotationOption.IsSet)
            {
                writer.WritePropertyName("avatarRotation");
                JsonSerializer.Serialize(writer, createCharacterRequest.AvatarRotation, jsonSerializerOptions);
            }
            if (createCharacterRequest.EnvironmentPresetOption.IsSet)
                writer.WriteString("environmentPreset", createCharacterRequest.EnvironmentPreset);
        }
    }
}
