/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetChatResponseMessagesInner
    /// </summary>
    [DataContract(Name = "GetChatResponse_messages_inner")]
    public partial class GetChatResponseMessagesInner
    {
        /// <summary>
        /// Defines Role
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RoleEnum
        {
            /// <summary>
            /// Enum User for value: user
            /// </summary>
            [EnumMember(Value = "user")]
            User = 1,

            /// <summary>
            /// Enum Assistant for value: assistant
            /// </summary>
            [EnumMember(Value = "assistant")]
            Assistant = 2,

            /// <summary>
            /// Enum System for value: system
            /// </summary>
            [EnumMember(Value = "system")]
            System = 3
        }


        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [DataMember(Name = "role", IsRequired = true, EmitDefaultValue = true)]
        public RoleEnum Role { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetChatResponseMessagesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetChatResponseMessagesInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetChatResponseMessagesInner" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="chatId">chatId (required).</param>
        /// <param name="role">role (required).</param>
        /// <param name="content">content (required).</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="tokenCount">tokenCount.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="citations">citations.</param>
        /// <param name="citationsLoading">citationsLoading.</param>
        public GetChatResponseMessagesInner(string id = default, string chatId = default, RoleEnum role = default, string content = default, DateTime createdAt = default, DateTime timestamp = default, decimal tokenCount = default, Dictionary<string, Object> metadata = default, List<GetChatResponseMessagesInnerCitationsInner> citations = default, bool citationsLoading = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for GetChatResponseMessagesInner and cannot be null");
            }
            this.Id = id;
            // to ensure "chatId" is required (not null)
            if (chatId == null)
            {
                throw new ArgumentNullException("chatId is a required property for GetChatResponseMessagesInner and cannot be null");
            }
            this.ChatId = chatId;
            this.Role = role;
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for GetChatResponseMessagesInner and cannot be null");
            }
            this.Content = content;
            this.CreatedAt = createdAt;
            this.Timestamp = timestamp;
            this.TokenCount = tokenCount;
            this.Metadata = metadata;
            this.Citations = citations;
            this.CitationsLoading = citationsLoading;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ChatId
        /// </summary>
        [DataMember(Name = "chatId", IsRequired = true, EmitDefaultValue = true)]
        public string ChatId { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public string Content { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets TokenCount
        /// </summary>
        [DataMember(Name = "tokenCount", EmitDefaultValue = false)]
        public decimal TokenCount { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Citations
        /// </summary>
        [DataMember(Name = "citations", EmitDefaultValue = false)]
        public List<GetChatResponseMessagesInnerCitationsInner> Citations { get; set; }

        /// <summary>
        /// Gets or Sets CitationsLoading
        /// </summary>
        [DataMember(Name = "citationsLoading", EmitDefaultValue = true)]
        public bool CitationsLoading { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetChatResponseMessagesInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ChatId: ").Append(ChatId).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  TokenCount: ").Append(TokenCount).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Citations: ").Append(Citations).Append("\n");
            sb.Append("  CitationsLoading: ").Append(CitationsLoading).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
