// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetModerationStatsResponse
    /// </summary>
    public partial class GetModerationStatsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModerationStatsResponse" /> class.
        /// </summary>
        /// <param name="totalFlags">totalFlags</param>
        /// <param name="flagsByCategory">flagsByCategory</param>
        /// <param name="recentFlags">recentFlags</param>
        /// <param name="reasonBreakdown">reasonBreakdown</param>
        [JsonConstructor]
        public GetModerationStatsResponse(decimal totalFlags, Dictionary<string, decimal> flagsByCategory, decimal recentFlags, Option<Dictionary<string, decimal>?> reasonBreakdown = default)
        {
            TotalFlags = totalFlags;
            FlagsByCategory = flagsByCategory;
            RecentFlags = recentFlags;
            ReasonBreakdownOption = reasonBreakdown;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets TotalFlags
        /// </summary>
        [JsonPropertyName("totalFlags")]
        public decimal TotalFlags { get; set; }

        /// <summary>
        /// Gets or Sets FlagsByCategory
        /// </summary>
        [JsonPropertyName("flagsByCategory")]
        public Dictionary<string, decimal> FlagsByCategory { get; set; }

        /// <summary>
        /// Gets or Sets RecentFlags
        /// </summary>
        [JsonPropertyName("recentFlags")]
        public decimal RecentFlags { get; set; }

        /// <summary>
        /// Used to track the state of ReasonBreakdown
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, decimal>?> ReasonBreakdownOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReasonBreakdown
        /// </summary>
        [JsonPropertyName("reasonBreakdown")]
        public Dictionary<string, decimal>? ReasonBreakdown { get { return this.ReasonBreakdownOption; } set { this.ReasonBreakdownOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetModerationStatsResponse {\n");
            sb.Append("  TotalFlags: ").Append(TotalFlags).Append("\n");
            sb.Append("  FlagsByCategory: ").Append(FlagsByCategory).Append("\n");
            sb.Append("  RecentFlags: ").Append(RecentFlags).Append("\n");
            sb.Append("  ReasonBreakdown: ").Append(ReasonBreakdown).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetModerationStatsResponse" />
    /// </summary>
    public class GetModerationStatsResponseJsonConverter : JsonConverter<GetModerationStatsResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetModerationStatsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetModerationStatsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> totalFlags = default;
            Option<Dictionary<string, decimal>?> flagsByCategory = default;
            Option<decimal?> recentFlags = default;
            Option<Dictionary<string, decimal>?> reasonBreakdown = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "totalFlags":
                            totalFlags = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "flagsByCategory":
                            flagsByCategory = new Option<Dictionary<string, decimal>?>(JsonSerializer.Deserialize<Dictionary<string, decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "recentFlags":
                            recentFlags = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "reasonBreakdown":
                            reasonBreakdown = new Option<Dictionary<string, decimal>?>(JsonSerializer.Deserialize<Dictionary<string, decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!totalFlags.IsSet)
                throw new ArgumentException("Property is required for class GetModerationStatsResponse.", nameof(totalFlags));

            if (!flagsByCategory.IsSet)
                throw new ArgumentException("Property is required for class GetModerationStatsResponse.", nameof(flagsByCategory));

            if (!recentFlags.IsSet)
                throw new ArgumentException("Property is required for class GetModerationStatsResponse.", nameof(recentFlags));

            if (totalFlags.IsSet && totalFlags.Value == null)
                throw new ArgumentNullException(nameof(totalFlags), "Property is not nullable for class GetModerationStatsResponse.");

            if (flagsByCategory.IsSet && flagsByCategory.Value == null)
                throw new ArgumentNullException(nameof(flagsByCategory), "Property is not nullable for class GetModerationStatsResponse.");

            if (recentFlags.IsSet && recentFlags.Value == null)
                throw new ArgumentNullException(nameof(recentFlags), "Property is not nullable for class GetModerationStatsResponse.");

            if (reasonBreakdown.IsSet && reasonBreakdown.Value == null)
                throw new ArgumentNullException(nameof(reasonBreakdown), "Property is not nullable for class GetModerationStatsResponse.");

            return new GetModerationStatsResponse(totalFlags.Value!.Value!, flagsByCategory.Value!, recentFlags.Value!.Value!, reasonBreakdown);
        }

        /// <summary>
        /// Serializes a <see cref="GetModerationStatsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getModerationStatsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetModerationStatsResponse getModerationStatsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getModerationStatsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetModerationStatsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getModerationStatsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetModerationStatsResponse getModerationStatsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getModerationStatsResponse.FlagsByCategory == null)
                throw new ArgumentNullException(nameof(getModerationStatsResponse.FlagsByCategory), "Property is required for class GetModerationStatsResponse.");

            if (getModerationStatsResponse.ReasonBreakdownOption.IsSet && getModerationStatsResponse.ReasonBreakdown == null)
                throw new ArgumentNullException(nameof(getModerationStatsResponse.ReasonBreakdown), "Property is required for class GetModerationStatsResponse.");

            writer.WriteNumber("totalFlags", getModerationStatsResponse.TotalFlags);

            writer.WritePropertyName("flagsByCategory");
            JsonSerializer.Serialize(writer, getModerationStatsResponse.FlagsByCategory, jsonSerializerOptions);
            writer.WriteNumber("recentFlags", getModerationStatsResponse.RecentFlags);

            if (getModerationStatsResponse.ReasonBreakdownOption.IsSet)
            {
                writer.WritePropertyName("reasonBreakdown");
                JsonSerializer.Serialize(writer, getModerationStatsResponse.ReasonBreakdown, jsonSerializerOptions);
            }
        }
    }
}
