/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetModerationLogsRequest
    /// </summary>
    [DataContract(Name = "GetModerationLogsRequest")]
    public partial class GetModerationLogsRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModerationLogsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetModerationLogsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModerationLogsRequest" /> class.
        /// </summary>
        /// <param name="userId">userId.</param>
        /// <param name="characterId">characterId.</param>
        /// <param name="limit">limit (required) (default to 50M).</param>
        /// <param name="offset">offset (required) (default to 0M).</param>
        public GetModerationLogsRequest(string userId = default, string characterId = default, decimal limit = 50M, decimal offset = 0M)
        {
            this.Limit = limit;
            this.Offset = offset;
            this.UserId = userId;
            this.CharacterId = characterId;
        }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets CharacterId
        /// </summary>
        [DataMember(Name = "characterId", EmitDefaultValue = false)]
        public string CharacterId { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Gets or Sets Offset
        /// </summary>
        [DataMember(Name = "offset", IsRequired = true, EmitDefaultValue = true)]
        public decimal Offset { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetModerationLogsRequest {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  CharacterId: ").Append(CharacterId).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
