// <auto-generated>
/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetModerationStatsRequest
    /// </summary>
    public partial class GetModerationStatsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModerationStatsRequest" /> class.
        /// </summary>
        /// <param name="userId">userId</param>
        /// <param name="characterId">characterId</param>
        [JsonConstructor]
        public GetModerationStatsRequest(Option<string?> userId = default, Option<string?> characterId = default)
        {
            UserIdOption = userId;
            CharacterIdOption = characterId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("userId")]
        public string? UserId { get { return this.UserIdOption; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CharacterId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CharacterIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CharacterId
        /// </summary>
        [JsonPropertyName("characterId")]
        public string? CharacterId { get { return this.CharacterIdOption; } set { this.CharacterIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetModerationStatsRequest {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  CharacterId: ").Append(CharacterId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetModerationStatsRequest" />
    /// </summary>
    public class GetModerationStatsRequestJsonConverter : JsonConverter<GetModerationStatsRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetModerationStatsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetModerationStatsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> userId = default;
            Option<string?> characterId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "userId":
                            userId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "characterId":
                            characterId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class GetModerationStatsRequest.");

            if (characterId.IsSet && characterId.Value == null)
                throw new ArgumentNullException(nameof(characterId), "Property is not nullable for class GetModerationStatsRequest.");

            return new GetModerationStatsRequest(userId, characterId);
        }

        /// <summary>
        /// Serializes a <see cref="GetModerationStatsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getModerationStatsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetModerationStatsRequest getModerationStatsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getModerationStatsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetModerationStatsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getModerationStatsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetModerationStatsRequest getModerationStatsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getModerationStatsRequest.UserIdOption.IsSet && getModerationStatsRequest.UserId == null)
                throw new ArgumentNullException(nameof(getModerationStatsRequest.UserId), "Property is required for class GetModerationStatsRequest.");

            if (getModerationStatsRequest.CharacterIdOption.IsSet && getModerationStatsRequest.CharacterId == null)
                throw new ArgumentNullException(nameof(getModerationStatsRequest.CharacterId), "Property is required for class GetModerationStatsRequest.");

            if (getModerationStatsRequest.UserIdOption.IsSet)
                writer.WriteString("userId", getModerationStatsRequest.UserId);

            if (getModerationStatsRequest.CharacterIdOption.IsSet)
                writer.WriteString("characterId", getModerationStatsRequest.CharacterId);
        }
    }
}
