/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetModerationLogsResponseLogsInner
    /// </summary>
    [DataContract(Name = "GetModerationLogsResponse_logs_inner")]
    public partial class GetModerationLogsResponseLogsInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModerationLogsResponseLogsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetModerationLogsResponseLogsInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModerationLogsResponseLogsInner" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="userId">userId (required).</param>
        /// <param name="characterId">characterId (required).</param>
        /// <param name="chatId">chatId (required).</param>
        /// <param name="flagged">flagged (required).</param>
        /// <param name="categories">categories (required).</param>
        /// <param name="categoryScores">categoryScores (required).</param>
        /// <param name="reason">reason (required).</param>
        /// <param name="originalMessage">originalMessage (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        public GetModerationLogsResponseLogsInner(string id = default, string userId = default, string characterId = default, string chatId = default, bool flagged = default, Dictionary<string, bool> categories = default, Dictionary<string, decimal> categoryScores = default, string reason = default, string originalMessage = default, string createdAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.Id = id;
            // to ensure "userId" is required (not null)
            if (userId == null)
            {
                throw new ArgumentNullException("userId is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.UserId = userId;
            // to ensure "characterId" is required (not null)
            if (characterId == null)
            {
                throw new ArgumentNullException("characterId is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.CharacterId = characterId;
            // to ensure "chatId" is required (not null)
            if (chatId == null)
            {
                throw new ArgumentNullException("chatId is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.ChatId = chatId;
            this.Flagged = flagged;
            // to ensure "categories" is required (not null)
            if (categories == null)
            {
                throw new ArgumentNullException("categories is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.Categories = categories;
            // to ensure "categoryScores" is required (not null)
            if (categoryScores == null)
            {
                throw new ArgumentNullException("categoryScores is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.CategoryScores = categoryScores;
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new ArgumentNullException("reason is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.Reason = reason;
            // to ensure "originalMessage" is required (not null)
            if (originalMessage == null)
            {
                throw new ArgumentNullException("originalMessage is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.OriginalMessage = originalMessage;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for GetModerationLogsResponseLogsInner and cannot be null");
            }
            this.CreatedAt = createdAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets CharacterId
        /// </summary>
        [DataMember(Name = "characterId", IsRequired = true, EmitDefaultValue = true)]
        public string CharacterId { get; set; }

        /// <summary>
        /// Gets or Sets ChatId
        /// </summary>
        [DataMember(Name = "chatId", IsRequired = true, EmitDefaultValue = true)]
        public string ChatId { get; set; }

        /// <summary>
        /// Gets or Sets Flagged
        /// </summary>
        [DataMember(Name = "flagged", IsRequired = true, EmitDefaultValue = true)]
        public bool Flagged { get; set; }

        /// <summary>
        /// Gets or Sets Categories
        /// </summary>
        [DataMember(Name = "categories", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, bool> Categories { get; set; }

        /// <summary>
        /// Gets or Sets CategoryScores
        /// </summary>
        [DataMember(Name = "categoryScores", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, decimal> CategoryScores { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", IsRequired = true, EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets OriginalMessage
        /// </summary>
        [DataMember(Name = "originalMessage", IsRequired = true, EmitDefaultValue = true)]
        public string OriginalMessage { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetModerationLogsResponseLogsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  CharacterId: ").Append(CharacterId).Append("\n");
            sb.Append("  ChatId: ").Append(ChatId).Append("\n");
            sb.Append("  Flagged: ").Append(Flagged).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  CategoryScores: ").Append(CategoryScores).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  OriginalMessage: ").Append(OriginalMessage).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
