// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetSuperadminsResponseInput
    /// </summary>
    public partial class GetSuperadminsResponseInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSuperadminsResponseInput" /> class.
        /// </summary>
        /// <param name="users">users</param>
        [JsonConstructor]
        public GetSuperadminsResponseInput(List<UpdateUserResponseInput> users)
        {
            Users = users;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Users
        /// </summary>
        [JsonPropertyName("users")]
        public List<UpdateUserResponseInput> Users { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSuperadminsResponseInput {\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSuperadminsResponseInput" />
    /// </summary>
    public class GetSuperadminsResponseInputJsonConverter : JsonConverter<GetSuperadminsResponseInput>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSuperadminsResponseInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSuperadminsResponseInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<UpdateUserResponseInput>?> users = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "users":
                            users = new Option<List<UpdateUserResponseInput>?>(JsonSerializer.Deserialize<List<UpdateUserResponseInput>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!users.IsSet)
                throw new ArgumentException("Property is required for class GetSuperadminsResponseInput.", nameof(users));

            if (users.IsSet && users.Value == null)
                throw new ArgumentNullException(nameof(users), "Property is not nullable for class GetSuperadminsResponseInput.");

            return new GetSuperadminsResponseInput(users.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetSuperadminsResponseInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSuperadminsResponseInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSuperadminsResponseInput getSuperadminsResponseInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSuperadminsResponseInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSuperadminsResponseInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSuperadminsResponseInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSuperadminsResponseInput getSuperadminsResponseInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSuperadminsResponseInput.Users == null)
                throw new ArgumentNullException(nameof(getSuperadminsResponseInput.Users), "Property is required for class GetSuperadminsResponseInput.");

            writer.WritePropertyName("users");
            JsonSerializer.Serialize(writer, getSuperadminsResponseInput.Users, jsonSerializerOptions);
        }
    }
}
