// <auto-generated>
/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetSTTLanguagesResponse
    /// </summary>
    public partial class GetSTTLanguagesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSTTLanguagesResponse" /> class.
        /// </summary>
        /// <param name="languages">languages</param>
        [JsonConstructor]
        public GetSTTLanguagesResponse(List<GetSTTLanguagesResponseLanguagesInner> languages)
        {
            Languages = languages;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Languages
        /// </summary>
        [JsonPropertyName("languages")]
        public List<GetSTTLanguagesResponseLanguagesInner> Languages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSTTLanguagesResponse {\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSTTLanguagesResponse" />
    /// </summary>
    public class GetSTTLanguagesResponseJsonConverter : JsonConverter<GetSTTLanguagesResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSTTLanguagesResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSTTLanguagesResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<GetSTTLanguagesResponseLanguagesInner>?> languages = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "languages":
                            languages = new Option<List<GetSTTLanguagesResponseLanguagesInner>?>(JsonSerializer.Deserialize<List<GetSTTLanguagesResponseLanguagesInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!languages.IsSet)
                throw new ArgumentException("Property is required for class GetSTTLanguagesResponse.", nameof(languages));

            if (languages.IsSet && languages.Value == null)
                throw new ArgumentNullException(nameof(languages), "Property is not nullable for class GetSTTLanguagesResponse.");

            return new GetSTTLanguagesResponse(languages.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetSTTLanguagesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSTTLanguagesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSTTLanguagesResponse getSTTLanguagesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSTTLanguagesResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSTTLanguagesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSTTLanguagesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSTTLanguagesResponse getSTTLanguagesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSTTLanguagesResponse.Languages == null)
                throw new ArgumentNullException(nameof(getSTTLanguagesResponse.Languages), "Property is required for class GetSTTLanguagesResponse.");

            writer.WritePropertyName("languages");
            JsonSerializer.Serialize(writer, getSTTLanguagesResponse.Languages, jsonSerializerOptions);
        }
    }
}
