// <auto-generated>
/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetUserFilesResponseInputFilesInner
    /// </summary>
    public partial class GetUserFilesResponseInputFilesInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserFilesResponseInputFilesInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="filename">filename</param>
        /// <param name="userId">userId</param>
        /// <param name="originalName">originalName</param>
        /// <param name="mimeType">mimeType</param>
        /// <param name="fileSize">fileSize</param>
        /// <param name="fileType">fileType</param>
        /// <param name="status">status</param>
        /// <param name="s3Key">s3Key</param>
        /// <param name="url">url</param>
        /// <param name="openaiFileId">openaiFileId</param>
        /// <param name="usageType">usageType</param>
        /// <param name="characterId">characterId</param>
        /// <param name="organizationId">organizationId</param>
        /// <param name="folderId">folderId</param>
        /// <param name="createdAt">createdAt</param>
        [JsonConstructor]
        public GetUserFilesResponseInputFilesInner(Guid id, string filename, string userId, Option<string?> originalName = default, Option<string?> mimeType = default, Option<decimal?> fileSize = default, Option<FileTypeEnum?> fileType = default, Option<StatusEnum?> status = default, Option<string?> s3Key = default, Option<string?> url = default, Option<string?> openaiFileId = default, Option<UsageTypeEnum?> usageType = default, Option<Guid?> characterId = default, Option<Guid?> organizationId = default, Option<Guid?> folderId = default, Option<Object?> createdAt = default)
        {
            Id = id;
            Filename = filename;
            UserId = userId;
            OriginalNameOption = originalName;
            MimeTypeOption = mimeType;
            FileSizeOption = fileSize;
            FileTypeOption = fileType;
            StatusOption = status;
            S3KeyOption = s3Key;
            UrlOption = url;
            OpenaiFileIdOption = openaiFileId;
            UsageTypeOption = usageType;
            CharacterIdOption = characterId;
            OrganizationIdOption = organizationId;
            FolderIdOption = folderId;
            CreatedAtOption = createdAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines FileType
        /// </summary>
        public enum FileTypeEnum
        {
            /// <summary>
            /// Enum Document for value: document
            /// </summary>
            Document = 1,

            /// <summary>
            /// Enum Image for value: image
            /// </summary>
            Image = 2,

            /// <summary>
            /// Enum Audio for value: audio
            /// </summary>
            Audio = 3,

            /// <summary>
            /// Enum Video for value: video
            /// </summary>
            Video = 4,

            /// <summary>
            /// Enum Avatar for value: avatar
            /// </summary>
            Avatar = 5,

            /// <summary>
            /// Enum Model for value: model
            /// </summary>
            Model = 6,

            /// <summary>
            /// Enum Other for value: other
            /// </summary>
            Other = 7
        }

        /// <summary>
        /// Returns a <see cref="FileTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FileTypeEnum FileTypeEnumFromString(string value)
        {
            if (value.Equals("document"))
                return FileTypeEnum.Document;

            if (value.Equals("image"))
                return FileTypeEnum.Image;

            if (value.Equals("audio"))
                return FileTypeEnum.Audio;

            if (value.Equals("video"))
                return FileTypeEnum.Video;

            if (value.Equals("avatar"))
                return FileTypeEnum.Avatar;

            if (value.Equals("model"))
                return FileTypeEnum.Model;

            if (value.Equals("other"))
                return FileTypeEnum.Other;

            throw new NotImplementedException($"Could not convert value to type FileTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FileTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FileTypeEnum? FileTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("document"))
                return FileTypeEnum.Document;

            if (value.Equals("image"))
                return FileTypeEnum.Image;

            if (value.Equals("audio"))
                return FileTypeEnum.Audio;

            if (value.Equals("video"))
                return FileTypeEnum.Video;

            if (value.Equals("avatar"))
                return FileTypeEnum.Avatar;

            if (value.Equals("model"))
                return FileTypeEnum.Model;

            if (value.Equals("other"))
                return FileTypeEnum.Other;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FileTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FileTypeEnumToJsonValue(FileTypeEnum? value)
        {
            if (value == FileTypeEnum.Document)
                return "document";

            if (value == FileTypeEnum.Image)
                return "image";

            if (value == FileTypeEnum.Audio)
                return "audio";

            if (value == FileTypeEnum.Video)
                return "video";

            if (value == FileTypeEnum.Avatar)
                return "avatar";

            if (value == FileTypeEnum.Model)
                return "model";

            if (value == FileTypeEnum.Other)
                return "other";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of FileType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FileTypeEnum?> FileTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FileType
        /// </summary>
        [JsonPropertyName("fileType")]
        public FileTypeEnum? FileType { get { return this.FileTypeOption.Value; } set { this.FileTypeOption = new(value); } }

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            Pending = 1,

            /// <summary>
            /// Enum Processing for value: processing
            /// </summary>
            Processing = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            Completed = 3,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            Failed = 4
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("processing"))
                return StatusEnum.Processing;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return StatusEnum.Pending;

            if (value.Equals("processing"))
                return StatusEnum.Processing;

            if (value.Equals("completed"))
                return StatusEnum.Completed;

            if (value.Equals("failed"))
                return StatusEnum.Failed;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Pending)
                return "pending";

            if (value == StatusEnum.Processing)
                return "processing";

            if (value == StatusEnum.Completed)
                return "completed";

            if (value == StatusEnum.Failed)
                return "failed";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Defines UsageType
        /// </summary>
        public enum UsageTypeEnum
        {
            /// <summary>
            /// Enum Internal for value: internal
            /// </summary>
            Internal = 1,

            /// <summary>
            /// Enum Quotable for value: quotable
            /// </summary>
            Quotable = 2,

            /// <summary>
            /// Enum Public for value: public
            /// </summary>
            Public = 3
        }

        /// <summary>
        /// Returns a <see cref="UsageTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static UsageTypeEnum UsageTypeEnumFromString(string value)
        {
            if (value.Equals("internal"))
                return UsageTypeEnum.Internal;

            if (value.Equals("quotable"))
                return UsageTypeEnum.Quotable;

            if (value.Equals("public"))
                return UsageTypeEnum.Public;

            throw new NotImplementedException($"Could not convert value to type UsageTypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="UsageTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static UsageTypeEnum? UsageTypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("internal"))
                return UsageTypeEnum.Internal;

            if (value.Equals("quotable"))
                return UsageTypeEnum.Quotable;

            if (value.Equals("public"))
                return UsageTypeEnum.Public;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="UsageTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string? UsageTypeEnumToJsonValue(UsageTypeEnum? value)
        {
            if (value == null)
                return null;

            if (value == UsageTypeEnum.Internal)
                return "internal";

            if (value == UsageTypeEnum.Quotable)
                return "quotable";

            if (value == UsageTypeEnum.Public)
                return "public";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of UsageType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<UsageTypeEnum?> UsageTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets UsageType
        /// </summary>
        [JsonPropertyName("usageType")]
        public UsageTypeEnum? UsageType { get { return this.UsageTypeOption.Value; } set { this.UsageTypeOption = new(value); } }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [JsonPropertyName("filename")]
        public string Filename { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("userId")]
        public string UserId { get; set; }

        /// <summary>
        /// Used to track the state of OriginalName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OriginalNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets OriginalName
        /// </summary>
        [JsonPropertyName("originalName")]
        public string? OriginalName { get { return this.OriginalNameOption; } set { this.OriginalNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of MimeType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MimeTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets MimeType
        /// </summary>
        [JsonPropertyName("mimeType")]
        public string? MimeType { get { return this.MimeTypeOption; } set { this.MimeTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of FileSize
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> FileSizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FileSize
        /// </summary>
        [JsonPropertyName("fileSize")]
        public decimal? FileSize { get { return this.FileSizeOption; } set { this.FileSizeOption = new(value); } }

        /// <summary>
        /// Used to track the state of S3Key
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> S3KeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets S3Key
        /// </summary>
        [JsonPropertyName("s3Key")]
        public string? S3Key { get { return this.S3KeyOption; } set { this.S3KeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of OpenaiFileId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OpenaiFileIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OpenaiFileId
        /// </summary>
        [JsonPropertyName("openaiFileId")]
        public string? OpenaiFileId { get { return this.OpenaiFileIdOption; } set { this.OpenaiFileIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CharacterId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> CharacterIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CharacterId
        /// </summary>
        [JsonPropertyName("characterId")]
        public Guid? CharacterId { get { return this.CharacterIdOption; } set { this.CharacterIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrganizationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> OrganizationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [JsonPropertyName("organizationId")]
        public Guid? OrganizationId { get { return this.OrganizationIdOption; } set { this.OrganizationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FolderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> FolderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets FolderId
        /// </summary>
        [JsonPropertyName("folderId")]
        public Guid? FolderId { get { return this.FolderIdOption; } set { this.FolderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> CreatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public Object? CreatedAt { get { return this.CreatedAtOption; } set { this.CreatedAtOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetUserFilesResponseInputFilesInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  OriginalName: ").Append(OriginalName).Append("\n");
            sb.Append("  MimeType: ").Append(MimeType).Append("\n");
            sb.Append("  FileSize: ").Append(FileSize).Append("\n");
            sb.Append("  FileType: ").Append(FileType).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  S3Key: ").Append(S3Key).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  OpenaiFileId: ").Append(OpenaiFileId).Append("\n");
            sb.Append("  UsageType: ").Append(UsageType).Append("\n");
            sb.Append("  CharacterId: ").Append(CharacterId).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  FolderId: ").Append(FolderId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (Guid) pattern
            Regex regexId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

            if (!regexId.Match(this.Id.ToString()).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Id, must match a pattern of " + regexId, new [] { "Id" });
            }
            if (this.CharacterIdOption.Value != null){
                // CharacterId (Guid) pattern
                Regex regexCharacterId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

                if (this.CharacterIdOption.Value != null &&!regexCharacterId.Match(this.CharacterIdOption.Value.ToString()!).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CharacterId, must match a pattern of " + regexCharacterId, new [] { "CharacterId" });
                }
            }

            if (this.OrganizationIdOption.Value != null){
                // OrganizationId (Guid) pattern
                Regex regexOrganizationId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

                if (this.OrganizationIdOption.Value != null &&!regexOrganizationId.Match(this.OrganizationIdOption.Value.ToString()!).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for OrganizationId, must match a pattern of " + regexOrganizationId, new [] { "OrganizationId" });
                }
            }

            if (this.FolderIdOption.Value != null){
                // FolderId (Guid) pattern
                Regex regexFolderId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

                if (this.FolderIdOption.Value != null &&!regexFolderId.Match(this.FolderIdOption.Value.ToString()!).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FolderId, must match a pattern of " + regexFolderId, new [] { "FolderId" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetUserFilesResponseInputFilesInner" />
    /// </summary>
    public class GetUserFilesResponseInputFilesInnerJsonConverter : JsonConverter<GetUserFilesResponseInputFilesInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetUserFilesResponseInputFilesInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetUserFilesResponseInputFilesInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> filename = default;
            Option<string?> userId = default;
            Option<string?> originalName = default;
            Option<string?> mimeType = default;
            Option<decimal?> fileSize = default;
            Option<GetUserFilesResponseInputFilesInner.FileTypeEnum?> fileType = default;
            Option<GetUserFilesResponseInputFilesInner.StatusEnum?> status = default;
            Option<string?> s3Key = default;
            Option<string?> url = default;
            Option<string?> openaiFileId = default;
            Option<GetUserFilesResponseInputFilesInner.UsageTypeEnum?> usageType = default;
            Option<Guid?> characterId = default;
            Option<Guid?> organizationId = default;
            Option<Guid?> folderId = default;
            Option<Object?> createdAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "filename":
                            filename = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "userId":
                            userId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "originalName":
                            originalName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mimeType":
                            mimeType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fileSize":
                            fileSize = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "fileType":
                            string? fileTypeRawValue = utf8JsonReader.GetString();
                            if (fileTypeRawValue != null)
                                fileType = new Option<GetUserFilesResponseInputFilesInner.FileTypeEnum?>(GetUserFilesResponseInputFilesInner.FileTypeEnumFromStringOrDefault(fileTypeRawValue));
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<GetUserFilesResponseInputFilesInner.StatusEnum?>(GetUserFilesResponseInputFilesInner.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "s3Key":
                            s3Key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "openaiFileId":
                            openaiFileId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "usageType":
                            string? usageTypeRawValue = utf8JsonReader.GetString();
                            if (usageTypeRawValue != null)
                                usageType = new Option<GetUserFilesResponseInputFilesInner.UsageTypeEnum?>(GetUserFilesResponseInputFilesInner.UsageTypeEnumFromStringOrDefault(usageTypeRawValue));
                            break;
                        case "characterId":
                            characterId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "organizationId":
                            organizationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "folderId":
                            folderId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "createdAt":
                            createdAt = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class GetUserFilesResponseInputFilesInner.", nameof(id));

            if (!filename.IsSet)
                throw new ArgumentException("Property is required for class GetUserFilesResponseInputFilesInner.", nameof(filename));

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class GetUserFilesResponseInputFilesInner.", nameof(userId));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (filename.IsSet && filename.Value == null)
                throw new ArgumentNullException(nameof(filename), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (originalName.IsSet && originalName.Value == null)
                throw new ArgumentNullException(nameof(originalName), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (mimeType.IsSet && mimeType.Value == null)
                throw new ArgumentNullException(nameof(mimeType), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (fileSize.IsSet && fileSize.Value == null)
                throw new ArgumentNullException(nameof(fileSize), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (fileType.IsSet && fileType.Value == null)
                throw new ArgumentNullException(nameof(fileType), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (s3Key.IsSet && s3Key.Value == null)
                throw new ArgumentNullException(nameof(s3Key), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class GetUserFilesResponseInputFilesInner.");

            return new GetUserFilesResponseInputFilesInner(id.Value!.Value!, filename.Value!, userId.Value!, originalName, mimeType, fileSize, fileType, status, s3Key, url, openaiFileId, usageType, characterId, organizationId, folderId, createdAt);
        }

        /// <summary>
        /// Serializes a <see cref="GetUserFilesResponseInputFilesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getUserFilesResponseInputFilesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetUserFilesResponseInputFilesInner getUserFilesResponseInputFilesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getUserFilesResponseInputFilesInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetUserFilesResponseInputFilesInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getUserFilesResponseInputFilesInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetUserFilesResponseInputFilesInner getUserFilesResponseInputFilesInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getUserFilesResponseInputFilesInner.Filename == null)
                throw new ArgumentNullException(nameof(getUserFilesResponseInputFilesInner.Filename), "Property is required for class GetUserFilesResponseInputFilesInner.");

            if (getUserFilesResponseInputFilesInner.UserId == null)
                throw new ArgumentNullException(nameof(getUserFilesResponseInputFilesInner.UserId), "Property is required for class GetUserFilesResponseInputFilesInner.");

            if (getUserFilesResponseInputFilesInner.OriginalNameOption.IsSet && getUserFilesResponseInputFilesInner.OriginalName == null)
                throw new ArgumentNullException(nameof(getUserFilesResponseInputFilesInner.OriginalName), "Property is required for class GetUserFilesResponseInputFilesInner.");

            if (getUserFilesResponseInputFilesInner.MimeTypeOption.IsSet && getUserFilesResponseInputFilesInner.MimeType == null)
                throw new ArgumentNullException(nameof(getUserFilesResponseInputFilesInner.MimeType), "Property is required for class GetUserFilesResponseInputFilesInner.");

            if (getUserFilesResponseInputFilesInner.S3KeyOption.IsSet && getUserFilesResponseInputFilesInner.S3Key == null)
                throw new ArgumentNullException(nameof(getUserFilesResponseInputFilesInner.S3Key), "Property is required for class GetUserFilesResponseInputFilesInner.");

            if (getUserFilesResponseInputFilesInner.UrlOption.IsSet && getUserFilesResponseInputFilesInner.Url == null)
                throw new ArgumentNullException(nameof(getUserFilesResponseInputFilesInner.Url), "Property is required for class GetUserFilesResponseInputFilesInner.");

            writer.WriteString("id", getUserFilesResponseInputFilesInner.Id);

            writer.WriteString("filename", getUserFilesResponseInputFilesInner.Filename);

            writer.WriteString("userId", getUserFilesResponseInputFilesInner.UserId);

            if (getUserFilesResponseInputFilesInner.OriginalNameOption.IsSet)
                writer.WriteString("originalName", getUserFilesResponseInputFilesInner.OriginalName);

            if (getUserFilesResponseInputFilesInner.MimeTypeOption.IsSet)
                writer.WriteString("mimeType", getUserFilesResponseInputFilesInner.MimeType);

            if (getUserFilesResponseInputFilesInner.FileSizeOption.IsSet)
                writer.WriteNumber("fileSize", getUserFilesResponseInputFilesInner.FileSizeOption.Value!.Value);

            var fileTypeRawValue = GetUserFilesResponseInputFilesInner.FileTypeEnumToJsonValue(getUserFilesResponseInputFilesInner.FileTypeOption.Value!.Value);
            writer.WriteString("fileType", fileTypeRawValue);
            var statusRawValue = GetUserFilesResponseInputFilesInner.StatusEnumToJsonValue(getUserFilesResponseInputFilesInner.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (getUserFilesResponseInputFilesInner.S3KeyOption.IsSet)
                writer.WriteString("s3Key", getUserFilesResponseInputFilesInner.S3Key);

            if (getUserFilesResponseInputFilesInner.UrlOption.IsSet)
                writer.WriteString("url", getUserFilesResponseInputFilesInner.Url);

            if (getUserFilesResponseInputFilesInner.OpenaiFileIdOption.IsSet)
                if (getUserFilesResponseInputFilesInner.OpenaiFileIdOption.Value != null)
                    writer.WriteString("openaiFileId", getUserFilesResponseInputFilesInner.OpenaiFileId);
                else
                    writer.WriteNull("openaiFileId");

            var usageTypeRawValue = GetUserFilesResponseInputFilesInner.UsageTypeEnumToJsonValue(getUserFilesResponseInputFilesInner.UsageTypeOption.Value!.Value);
            if (usageTypeRawValue != null)
                writer.WriteString("usageType", usageTypeRawValue);
            else
                writer.WriteNull("usageType");

            if (getUserFilesResponseInputFilesInner.CharacterIdOption.IsSet)
                if (getUserFilesResponseInputFilesInner.CharacterIdOption.Value != null)
                    writer.WriteString("characterId", getUserFilesResponseInputFilesInner.CharacterIdOption.Value!.Value);
                else
                    writer.WriteNull("characterId");

            if (getUserFilesResponseInputFilesInner.OrganizationIdOption.IsSet)
                if (getUserFilesResponseInputFilesInner.OrganizationIdOption.Value != null)
                    writer.WriteString("organizationId", getUserFilesResponseInputFilesInner.OrganizationIdOption.Value!.Value);
                else
                    writer.WriteNull("organizationId");

            if (getUserFilesResponseInputFilesInner.FolderIdOption.IsSet)
                if (getUserFilesResponseInputFilesInner.FolderIdOption.Value != null)
                    writer.WriteString("folderId", getUserFilesResponseInputFilesInner.FolderIdOption.Value!.Value);
                else
                    writer.WriteNull("folderId");

            if (getUserFilesResponseInputFilesInner.CreatedAtOption.IsSet)
                if (getUserFilesResponseInputFilesInner.CreatedAtOption.Value != null)
                {
                    writer.WritePropertyName("createdAt");
                    JsonSerializer.Serialize(writer, getUserFilesResponseInputFilesInner.CreatedAt, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("createdAt");
        }
    }
}
