/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// GetUserFilesResponseStorageInfo
    /// </summary>
    [DataContract(Name = "GetUserFilesResponse_storageInfo")]
    public partial class GetUserFilesResponseStorageInfo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserFilesResponseStorageInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetUserFilesResponseStorageInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserFilesResponseStorageInfo" /> class.
        /// </summary>
        /// <param name="used">used (required).</param>
        /// <param name="total">total (required).</param>
        /// <param name="available">available (required).</param>
        /// <param name="limits">limits.</param>
        public GetUserFilesResponseStorageInfo(decimal used = default, decimal total = default, decimal available = default, GetUserFilesResponseStorageInfoLimits limits = default)
        {
            this.Used = used;
            this.Total = total;
            this.Available = available;
            this.Limits = limits;
        }

        /// <summary>
        /// Gets or Sets Used
        /// </summary>
        [DataMember(Name = "used", IsRequired = true, EmitDefaultValue = true)]
        public decimal Used { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Gets or Sets Available
        /// </summary>
        [DataMember(Name = "available", IsRequired = true, EmitDefaultValue = true)]
        public decimal Available { get; set; }

        /// <summary>
        /// Gets or Sets Limits
        /// </summary>
        [DataMember(Name = "limits", EmitDefaultValue = false)]
        public GetUserFilesResponseStorageInfoLimits Limits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetUserFilesResponseStorageInfo {\n");
            sb.Append("  Used: ").Append(Used).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Validates the model properties and returns a list of validation errors.
        /// </summary>
        /// <returns>A list of validation error messages. Empty list if valid.</returns>
        public List<string> ValidateModel()
        {
            var errors = new List<string>();
            return errors;
        }
    }

}
