// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// HandbookAttachResponseInput
    /// </summary>
    public partial class HandbookAttachResponseInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HandbookAttachResponseInput" /> class.
        /// </summary>
        /// <param name="attached">attached</param>
        /// <param name="total">total</param>
        [JsonConstructor]
        public HandbookAttachResponseInput(decimal attached, decimal total)
        {
            Attached = attached;
            Total = total;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Attached
        /// </summary>
        [JsonPropertyName("attached")]
        public decimal Attached { get; set; }

        /// <summary>
        /// Gets or Sets Total
        /// </summary>
        [JsonPropertyName("total")]
        public decimal Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HandbookAttachResponseInput {\n");
            sb.Append("  Attached: ").Append(Attached).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HandbookAttachResponseInput" />
    /// </summary>
    public class HandbookAttachResponseInputJsonConverter : JsonConverter<HandbookAttachResponseInput>
    {
        /// <summary>
        /// Deserializes json to <see cref="HandbookAttachResponseInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override HandbookAttachResponseInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> attached = default;
            Option<decimal?> total = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "attached":
                            attached = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "total":
                            total = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!attached.IsSet)
                throw new ArgumentException("Property is required for class HandbookAttachResponseInput.", nameof(attached));

            if (!total.IsSet)
                throw new ArgumentException("Property is required for class HandbookAttachResponseInput.", nameof(total));

            if (attached.IsSet && attached.Value == null)
                throw new ArgumentNullException(nameof(attached), "Property is not nullable for class HandbookAttachResponseInput.");

            if (total.IsSet && total.Value == null)
                throw new ArgumentNullException(nameof(total), "Property is not nullable for class HandbookAttachResponseInput.");

            return new HandbookAttachResponseInput(attached.Value!.Value!, total.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="HandbookAttachResponseInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="handbookAttachResponseInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, HandbookAttachResponseInput handbookAttachResponseInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, handbookAttachResponseInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="HandbookAttachResponseInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="handbookAttachResponseInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, HandbookAttachResponseInput handbookAttachResponseInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("attached", handbookAttachResponseInput.Attached);

            writer.WriteNumber("total", handbookAttachResponseInput.Total);
        }
    }
}
