// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// KnowledgeFolderListResponseDataInner
    /// </summary>
    public partial class KnowledgeFolderListResponseDataInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KnowledgeFolderListResponseDataInner" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="organizationId">organizationId</param>
        /// <param name="name">name</param>
        /// <param name="isDefault">isDefault</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="description">description</param>
        /// <param name="createdBy">createdBy</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="counts">counts</param>
        [JsonConstructor]
        public KnowledgeFolderListResponseDataInner(string id, string organizationId, string name, bool isDefault, string createdAt, Option<string?> description = default, Option<string?> createdBy = default, Option<string?> updatedAt = default, Option<KnowledgeFolderListResponseDataInnerCounts?> counts = default)
        {
            Id = id;
            OrganizationId = organizationId;
            Name = name;
            IsDefault = isDefault;
            CreatedAt = createdAt;
            DescriptionOption = description;
            CreatedByOption = createdBy;
            UpdatedAtOption = updatedAt;
            CountsOption = counts;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [JsonPropertyName("organizationId")]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets IsDefault
        /// </summary>
        [JsonPropertyName("isDefault")]
        public bool IsDefault { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreatedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [JsonPropertyName("createdBy")]
        public string? CreatedBy { get { return this.CreatedByOption; } set { this.CreatedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of UpdatedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UpdatedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public string? UpdatedAt { get { return this.UpdatedAtOption; } set { this.UpdatedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of Counts
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<KnowledgeFolderListResponseDataInnerCounts?> CountsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Counts
        /// </summary>
        [JsonPropertyName("counts")]
        public KnowledgeFolderListResponseDataInnerCounts? Counts { get { return this.CountsOption; } set { this.CountsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KnowledgeFolderListResponseDataInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IsDefault: ").Append(IsDefault).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Counts: ").Append(Counts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="KnowledgeFolderListResponseDataInner" />
    /// </summary>
    public class KnowledgeFolderListResponseDataInnerJsonConverter : JsonConverter<KnowledgeFolderListResponseDataInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="KnowledgeFolderListResponseDataInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override KnowledgeFolderListResponseDataInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> organizationId = default;
            Option<string?> name = default;
            Option<bool?> isDefault = default;
            Option<string?> createdAt = default;
            Option<string?> description = default;
            Option<string?> createdBy = default;
            Option<string?> updatedAt = default;
            Option<KnowledgeFolderListResponseDataInnerCounts?> counts = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organizationId":
                            organizationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "isDefault":
                            isDefault = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "createdAt":
                            createdAt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "createdBy":
                            createdBy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "updatedAt":
                            updatedAt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "counts":
                            counts = new Option<KnowledgeFolderListResponseDataInnerCounts?>(JsonSerializer.Deserialize<KnowledgeFolderListResponseDataInnerCounts>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class KnowledgeFolderListResponseDataInner.", nameof(id));

            if (!organizationId.IsSet)
                throw new ArgumentException("Property is required for class KnowledgeFolderListResponseDataInner.", nameof(organizationId));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class KnowledgeFolderListResponseDataInner.", nameof(name));

            if (!isDefault.IsSet)
                throw new ArgumentException("Property is required for class KnowledgeFolderListResponseDataInner.", nameof(isDefault));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class KnowledgeFolderListResponseDataInner.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class KnowledgeFolderListResponseDataInner.");

            if (organizationId.IsSet && organizationId.Value == null)
                throw new ArgumentNullException(nameof(organizationId), "Property is not nullable for class KnowledgeFolderListResponseDataInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class KnowledgeFolderListResponseDataInner.");

            if (isDefault.IsSet && isDefault.Value == null)
                throw new ArgumentNullException(nameof(isDefault), "Property is not nullable for class KnowledgeFolderListResponseDataInner.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class KnowledgeFolderListResponseDataInner.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class KnowledgeFolderListResponseDataInner.");

            if (counts.IsSet && counts.Value == null)
                throw new ArgumentNullException(nameof(counts), "Property is not nullable for class KnowledgeFolderListResponseDataInner.");

            return new KnowledgeFolderListResponseDataInner(id.Value!, organizationId.Value!, name.Value!, isDefault.Value!.Value!, createdAt.Value!, description, createdBy, updatedAt, counts);
        }

        /// <summary>
        /// Serializes a <see cref="KnowledgeFolderListResponseDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="knowledgeFolderListResponseDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, KnowledgeFolderListResponseDataInner knowledgeFolderListResponseDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, knowledgeFolderListResponseDataInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="KnowledgeFolderListResponseDataInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="knowledgeFolderListResponseDataInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, KnowledgeFolderListResponseDataInner knowledgeFolderListResponseDataInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (knowledgeFolderListResponseDataInner.Id == null)
                throw new ArgumentNullException(nameof(knowledgeFolderListResponseDataInner.Id), "Property is required for class KnowledgeFolderListResponseDataInner.");

            if (knowledgeFolderListResponseDataInner.OrganizationId == null)
                throw new ArgumentNullException(nameof(knowledgeFolderListResponseDataInner.OrganizationId), "Property is required for class KnowledgeFolderListResponseDataInner.");

            if (knowledgeFolderListResponseDataInner.Name == null)
                throw new ArgumentNullException(nameof(knowledgeFolderListResponseDataInner.Name), "Property is required for class KnowledgeFolderListResponseDataInner.");

            if (knowledgeFolderListResponseDataInner.CreatedAt == null)
                throw new ArgumentNullException(nameof(knowledgeFolderListResponseDataInner.CreatedAt), "Property is required for class KnowledgeFolderListResponseDataInner.");

            if (knowledgeFolderListResponseDataInner.UpdatedAtOption.IsSet && knowledgeFolderListResponseDataInner.UpdatedAt == null)
                throw new ArgumentNullException(nameof(knowledgeFolderListResponseDataInner.UpdatedAt), "Property is required for class KnowledgeFolderListResponseDataInner.");

            if (knowledgeFolderListResponseDataInner.CountsOption.IsSet && knowledgeFolderListResponseDataInner.Counts == null)
                throw new ArgumentNullException(nameof(knowledgeFolderListResponseDataInner.Counts), "Property is required for class KnowledgeFolderListResponseDataInner.");

            writer.WriteString("id", knowledgeFolderListResponseDataInner.Id);

            writer.WriteString("organizationId", knowledgeFolderListResponseDataInner.OrganizationId);

            writer.WriteString("name", knowledgeFolderListResponseDataInner.Name);

            writer.WriteBoolean("isDefault", knowledgeFolderListResponseDataInner.IsDefault);

            writer.WriteString("createdAt", knowledgeFolderListResponseDataInner.CreatedAt);

            if (knowledgeFolderListResponseDataInner.DescriptionOption.IsSet)
                if (knowledgeFolderListResponseDataInner.DescriptionOption.Value != null)
                    writer.WriteString("description", knowledgeFolderListResponseDataInner.Description);
                else
                    writer.WriteNull("description");

            if (knowledgeFolderListResponseDataInner.CreatedByOption.IsSet)
                if (knowledgeFolderListResponseDataInner.CreatedByOption.Value != null)
                    writer.WriteString("createdBy", knowledgeFolderListResponseDataInner.CreatedBy);
                else
                    writer.WriteNull("createdBy");

            if (knowledgeFolderListResponseDataInner.UpdatedAtOption.IsSet)
                writer.WriteString("updatedAt", knowledgeFolderListResponseDataInner.UpdatedAt);

            if (knowledgeFolderListResponseDataInner.CountsOption.IsSet)
            {
                writer.WritePropertyName("counts");
                JsonSerializer.Serialize(writer, knowledgeFolderListResponseDataInner.Counts, jsonSerializerOptions);
            }
        }
    }
}
