/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// TTSSynthesizeRequestInput
    /// </summary>
    [DataContract(Name = "TTSSynthesizeRequestInput")]
    public partial class TTSSynthesizeRequestInput
    {
        /// <summary>
        /// Defines Service
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ServiceEnum
        {
            /// <summary>
            /// Enum Elevenlabs for value: elevenlabs
            /// </summary>
            [EnumMember(Value = "elevenlabs")]
            Elevenlabs = 1
        }


        /// <summary>
        /// Gets or Sets Service
        /// </summary>
        [DataMember(Name = "service", EmitDefaultValue = false)]
        public ServiceEnum? Service { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TTSSynthesizeRequestInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TTSSynthesizeRequestInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TTSSynthesizeRequestInput" /> class.
        /// </summary>
        /// <param name="text">text (required).</param>
        /// <param name="voice">voice.</param>
        /// <param name="service">service (default to ServiceEnum.Elevenlabs).</param>
        public TTSSynthesizeRequestInput(string text = default, string voice = default, ServiceEnum? service = ServiceEnum.Elevenlabs)
        {
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for TTSSynthesizeRequestInput and cannot be null");
            }
            this.Text = text;
            this.Voice = voice;
            this.Service = service;
        }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Voice
        /// </summary>
        [DataMember(Name = "voice", EmitDefaultValue = false)]
        public string Voice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TTSSynthesizeRequestInput {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Voice: ").Append(Voice).Append("\n");
            sb.Append("  Service: ").Append(Service).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
