// <auto-generated>
/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using AcademiiSdk.Client;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// UpdateCourseRequest
    /// </summary>
    public partial class UpdateCourseRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCourseRequest" /> class.
        /// </summary>
        /// <param name="topicId">topicId</param>
        /// <param name="name">name</param>
        /// <param name="code">code</param>
        /// <param name="description">description</param>
        /// <param name="sortOrder">sortOrder</param>
        /// <param name="enforceModuleOrder">enforceModuleOrder</param>
        /// <param name="organizationId">organizationId</param>
        /// <param name="status">status</param>
        /// <param name="isActive">isActive</param>
        [JsonConstructor]
        public UpdateCourseRequest(Option<Guid?> topicId = default, Option<string?> name = default, Option<string?> code = default, Option<string?> description = default, Option<long?> sortOrder = default, Option<bool?> enforceModuleOrder = default, Option<Guid?> organizationId = default, Option<string?> status = default, Option<bool?> isActive = default)
        {
            TopicIdOption = topicId;
            NameOption = name;
            CodeOption = code;
            DescriptionOption = description;
            SortOrderOption = sortOrder;
            EnforceModuleOrderOption = enforceModuleOrder;
            OrganizationIdOption = organizationId;
            StatusOption = status;
            IsActiveOption = isActive;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of TopicId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> TopicIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TopicId
        /// </summary>
        [JsonPropertyName("topicId")]
        public Guid? TopicId { get { return this.TopicIdOption; } set { this.TopicIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public string? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of SortOrder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SortOrderOption { get; private set; }

        /// <summary>
        /// Gets or Sets SortOrder
        /// </summary>
        [JsonPropertyName("sortOrder")]
        public long? SortOrder { get { return this.SortOrderOption; } set { this.SortOrderOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnforceModuleOrder
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnforceModuleOrderOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnforceModuleOrder
        /// </summary>
        [JsonPropertyName("enforceModuleOrder")]
        public bool? EnforceModuleOrder { get { return this.EnforceModuleOrderOption; } set { this.EnforceModuleOrderOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrganizationId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> OrganizationIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [JsonPropertyName("organizationId")]
        public Guid? OrganizationId { get { return this.OrganizationIdOption; } set { this.OrganizationIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCourseRequest {\n");
            sb.Append("  TopicId: ").Append(TopicId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  SortOrder: ").Append(SortOrder).Append("\n");
            sb.Append("  EnforceModuleOrder: ").Append(EnforceModuleOrder).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TopicId (Guid) pattern
            Regex regexTopicId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

            if (this.TopicIdOption.Value != null &&!regexTopicId.Match(this.TopicIdOption.Value.ToString()!).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TopicId, must match a pattern of " + regexTopicId, new [] { "TopicId" });
            }
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Code (string) minLength
            if (this.Code != null && this.Code.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Code, length must be greater than 1.", new [] { "Code" });
            }

            // SortOrder (long) maximum
            if (this.SortOrderOption.IsSet && this.SortOrderOption.Value > (long)9007199254740991)
            {
                yield return new ValidationResult("Invalid value for SortOrder, must be a value less than or equal to 9007199254740991.", new [] { "SortOrder" });
            }

            // SortOrder (long) minimum
            if (this.SortOrderOption.IsSet && this.SortOrderOption.Value < (long)0)
            {
                yield return new ValidationResult("Invalid value for SortOrder, must be a value greater than or equal to 0.", new [] { "SortOrder" });
            }

            // OrganizationId (Guid) pattern
            Regex regexOrganizationId = new Regex(@"^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$", RegexOptions.CultureInvariant);

            if (this.OrganizationIdOption.Value != null &&!regexOrganizationId.Match(this.OrganizationIdOption.Value.ToString()!).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for OrganizationId, must match a pattern of " + regexOrganizationId, new [] { "OrganizationId" });
            }
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateCourseRequest" />
    /// </summary>
    public class UpdateCourseRequestJsonConverter : JsonConverter<UpdateCourseRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateCourseRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateCourseRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> topicId = default;
            Option<string?> name = default;
            Option<string?> code = default;
            Option<string?> description = default;
            Option<long?> sortOrder = default;
            Option<bool?> enforceModuleOrder = default;
            Option<Guid?> organizationId = default;
            Option<string?> status = default;
            Option<bool?> isActive = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "topicId":
                            topicId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "code":
                            code = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sortOrder":
                            sortOrder = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "enforceModuleOrder":
                            enforceModuleOrder = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "organizationId":
                            organizationId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "isActive":
                            isActive = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (topicId.IsSet && topicId.Value == null)
                throw new ArgumentNullException(nameof(topicId), "Property is not nullable for class UpdateCourseRequest.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class UpdateCourseRequest.");

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class UpdateCourseRequest.");

            if (sortOrder.IsSet && sortOrder.Value == null)
                throw new ArgumentNullException(nameof(sortOrder), "Property is not nullable for class UpdateCourseRequest.");

            if (enforceModuleOrder.IsSet && enforceModuleOrder.Value == null)
                throw new ArgumentNullException(nameof(enforceModuleOrder), "Property is not nullable for class UpdateCourseRequest.");

            if (organizationId.IsSet && organizationId.Value == null)
                throw new ArgumentNullException(nameof(organizationId), "Property is not nullable for class UpdateCourseRequest.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class UpdateCourseRequest.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class UpdateCourseRequest.");

            return new UpdateCourseRequest(topicId, name, code, description, sortOrder, enforceModuleOrder, organizationId, status, isActive);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateCourseRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCourseRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateCourseRequest updateCourseRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateCourseRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateCourseRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateCourseRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateCourseRequest updateCourseRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateCourseRequest.NameOption.IsSet && updateCourseRequest.Name == null)
                throw new ArgumentNullException(nameof(updateCourseRequest.Name), "Property is required for class UpdateCourseRequest.");

            if (updateCourseRequest.CodeOption.IsSet && updateCourseRequest.Code == null)
                throw new ArgumentNullException(nameof(updateCourseRequest.Code), "Property is required for class UpdateCourseRequest.");

            if (updateCourseRequest.StatusOption.IsSet && updateCourseRequest.Status == null)
                throw new ArgumentNullException(nameof(updateCourseRequest.Status), "Property is required for class UpdateCourseRequest.");

            if (updateCourseRequest.TopicIdOption.IsSet)
                writer.WriteString("topicId", updateCourseRequest.TopicIdOption.Value!.Value);

            if (updateCourseRequest.NameOption.IsSet)
                writer.WriteString("name", updateCourseRequest.Name);

            if (updateCourseRequest.CodeOption.IsSet)
                writer.WriteString("code", updateCourseRequest.Code);

            if (updateCourseRequest.DescriptionOption.IsSet)
                if (updateCourseRequest.DescriptionOption.Value != null)
                    writer.WriteString("description", updateCourseRequest.Description);
                else
                    writer.WriteNull("description");

            if (updateCourseRequest.SortOrderOption.IsSet)
                writer.WriteNumber("sortOrder", updateCourseRequest.SortOrderOption.Value!.Value);

            if (updateCourseRequest.EnforceModuleOrderOption.IsSet)
                writer.WriteBoolean("enforceModuleOrder", updateCourseRequest.EnforceModuleOrderOption.Value!.Value);

            if (updateCourseRequest.OrganizationIdOption.IsSet)
                writer.WriteString("organizationId", updateCourseRequest.OrganizationIdOption.Value!.Value);

            if (updateCourseRequest.StatusOption.IsSet)
                writer.WriteString("status", updateCourseRequest.Status);

            if (updateCourseRequest.IsActiveOption.IsSet)
                writer.WriteBoolean("isActive", updateCourseRequest.IsActiveOption.Value!.Value);
        }
    }
}
