/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// UploadProfilePictureResponse
    /// </summary>
    [DataContract(Name = "UploadProfilePictureResponse")]
    public partial class UploadProfilePictureResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadProfilePictureResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UploadProfilePictureResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UploadProfilePictureResponse" /> class.
        /// </summary>
        /// <param name="photoURL">photoURL (required).</param>
        public UploadProfilePictureResponse(string photoURL = default)
        {
            // to ensure "photoURL" is required (not null)
            if (photoURL == null)
            {
                throw new ArgumentNullException("photoURL is a required property for UploadProfilePictureResponse and cannot be null");
            }
            this.PhotoURL = photoURL;
        }

        /// <summary>
        /// Gets or Sets PhotoURL
        /// </summary>
        [DataMember(Name = "photoURL", IsRequired = true, EmitDefaultValue = true)]
        public string PhotoURL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UploadProfilePictureResponse {\n");
            sb.Append("  PhotoURL: ").Append(PhotoURL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
