/*
 * Academii IPA API
 *
 * Full REST API for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// UpsertCharacterMeshLinkRequest
    /// </summary>
    [DataContract(Name = "UpsertCharacterMeshLinkRequest")]
    public partial class UpsertCharacterMeshLinkRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpsertCharacterMeshLinkRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpsertCharacterMeshLinkRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpsertCharacterMeshLinkRequest" /> class.
        /// </summary>
        /// <param name="meshName">meshName (required).</param>
        /// <param name="url">url (required).</param>
        /// <param name="description">description.</param>
        public UpsertCharacterMeshLinkRequest(string meshName = default, string url = default, string description = default)
        {
            // to ensure "meshName" is required (not null)
            if (meshName == null)
            {
                throw new ArgumentNullException("meshName is a required property for UpsertCharacterMeshLinkRequest and cannot be null");
            }
            this.MeshName = meshName;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for UpsertCharacterMeshLinkRequest and cannot be null");
            }
            this.Url = url;
            this.Description = description;
        }

        /// <summary>
        /// Gets or Sets MeshName
        /// </summary>
        [DataMember(Name = "meshName", IsRequired = true, EmitDefaultValue = true)]
        public string MeshName { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpsertCharacterMeshLinkRequest {\n");
            sb.Append("  MeshName: ").Append(MeshName).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
