/*
 * Academii IPA Unity SDK API
 *
 * Unity SDK specific API endpoints for the Academii IPA platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = AcademiiSdk.Client.OpenAPIDateConverter;

namespace AcademiiSdk.Model
{
    /// <summary>
    /// UserRegisterRequestInput
    /// </summary>
    [DataContract(Name = "UserRegisterRequestInput")]
    public partial class UserRegisterRequestInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRegisterRequestInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserRegisterRequestInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRegisterRequestInput" /> class.
        /// </summary>
        /// <param name="email">email (required).</param>
        /// <param name="password">password (required).</param>
        /// <param name="displayName">displayName.</param>
        public UserRegisterRequestInput(string email = default, string password = default, string displayName = default)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for UserRegisterRequestInput and cannot be null");
            }
            this.Email = email;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for UserRegisterRequestInput and cannot be null");
            }
            this.Password = password;
            this.DisplayName = displayName;
        }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "displayName", EmitDefaultValue = false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserRegisterRequestInput {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Validates the model properties and returns a list of validation errors.
        /// </summary>
        /// <returns>A list of validation error messages. Empty list if valid.</returns>
        public List<string> ValidateModel()
        {
            var errors = new List<string>();
                // Email (string) pattern
                Regex regexEmail = new Regex(@"^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$", RegexOptions.CultureInvariant);
                if (!regexEmail.Match(this.Email).Success)
                {
                    errors.Add("Invalid value for Email, must match a pattern of " + regexEmail);
                }

            // Password (string) minLength
            if (this.Password != null && this.Password.Length < 8)
            {
                errors.Add("Invalid value for Password, length must be greater than 8.");
            }

            return errors;
        }
    }

}
